### ISSUE TITLE
Deprecate the customized Broadleaf CsrfFilter in favor of Spring Security's out-of-the-box CSRF protection

### ISSUE THREAD

**Issue by phillipuniverse** [BroadleafCommerce/BroadleafCommerce#1117]
This only applies to Broadleaf 3.2 as that is the only release line that contains Spring Security 3.2+. See the configuration at http://docs.spring.io/spring-security/site/docs/3.2.5.RELEASE/reference/htmlsingle/#csrf. In this section there is also a note that says that CSRF protection will be enabled by default starting with Spring Security 4.0.

**Comment by phillipuniverse** [comment]
Mainly need to figure out what the impact is in Broadleaf esp. in regards to existing implementations

**Comment by cja769** [comment]
In order to get Spring's CSRF protection to work, the csrf tag needs to be added to the applicationContext-security.xml:

```
<sec:http ...>
...
 <sec:csrf />
...
</sec:http>
```

The things listed below need to be removed because they are no longer needed:

```
<sec:custom-filter ref="blCsrfFilter" before="FORM_LOGIN_FILTER"/>
<sec:custom-filter ref="blSessionFixationProtectionFilter" before="SESSION_MANAGEMENT_FILTER"/>
```
```
<bean id="blCsrfFilter" class="org.broadleafcommerce.common.security.handler.CsrfFilter" >
    <property name="excludedRequestPatterns">
        <list>
            <value>/null-checkout/**</value>
            <value>/null-giftcard/**</value>
            <value>/hosted/null-checkout/**</value>
        </list>
    </property>
</bean>
```

Everywhere there is ``` <blc:form> ``` needs to be changed to ``` <form> ```.

Also, as Philip said, a class needs to written for the <code>request-matcher</code> property in the csrf tag. The class will basically do what <code>org.broadleafcommerce.common.security.handler.CsrfFilter</code> did.

Lastly, Spring suggests to not use GET requests for logging out so we need to change that to where it is a POST with the CSRF token included in it. I suggest using a form to do so since Spring will automatically add the CSRF token in a hidden field for ever form.

**Comment by bpolster** [comment]
The analysis above doesn't seem to take into account how ajax posts will work.    (e.g. BLC.ajax() in BLC.js adds the CSRF filter to ajax calls.

I understand how <blc:form> automatically adds the CSRF token as a hidden field.    I am not following the mechanism that will alter the form and place the hidden field if the BLC CSRF process is removed.   Please explain how this will work with the new approach.

**Comment by bpolster** [comment]
I see how the mechanism works here for the form tag.

http://docs.spring.io/spring-security/site/docs/3.2.5.RELEASE/reference/htmlsingle/#csrf-include-csrf-token

That documentation indicates you can add the hidden field (like we do today) or you can rely on Thymeleaf or Spring-MVC.     When relying on Thymeleaf, it says to use the @EnableWebMvcSecurity annotation.    This looks to be using Spring configuration classes.    Do we know how to enable this with our "xml" based config.  

Question above on BLC.ajax and what we need to do there is still open.

**Comment by cja769** [comment]
```<sec:csrf /> ``` is the xml alternative to @EnableWebMvcSecurity.

As for the ajax calls it's explained at http://docs.spring.io/spring-security/site/docs/3.2.5.RELEASE/reference/htmlsingle/#csrf-include-csrf-token-ajax but I haven't actually tried to implement it yet.

**Comment by bpolster** [comment]
I recall us running into a problem similar to this ... 
http://docs.spring.io/spring-security/site/docs/3.2.5.RELEASE/reference/htmlsingle/#csrf-multipart 

@phillipuniverse Does this ring a bell?

**Comment by cja769** [comment]
I recall seeing somewhere that we had to deal with multipart and we dealt with it very similarly to how Spring suggests

**Comment by phillipuniverse** [comment]
@bpolster good catch, I had forgotten about that. We're actually doing that in our `FormProcessor`:

```java
if ("multipart/form-data".equalsIgnoreCase(element.getAttributeValueFromNormalizedName("enctype"))) {
    Expression expression = (Expression) StandardExpressions.getExpressionParser(arguments.getConfiguration())
            .parseExpression(arguments.getConfiguration(), arguments, element.getAttributeValueFromNormalizedName("th:action"));
    String action = (String) expression.execute(arguments.getConfiguration(), arguments);
    String csrfQueryParameter = "?" + eps.getCsrfTokenParameter() + "=" + csrfToken;
    element.removeAttribute("th:action");
    element.setAttribute("action", action + csrfQueryParameter);
}
```

This is basically the 2nd method from the section that you linked: http://docs.spring.io/spring-security/site/docs/3.2.5.RELEASE/reference/htmlsingle/#csrf-include-csrf-token-in-action.

@cja769 what is it the actual thing in Thymeleaf that adds the hidden input for the csrf token?

The easy test here is uploading an image in the admin.

**Comment by cja769** [comment]
@phillipuniverse Thymeleaf uses the RequestDataValueProcessor to determine what to do for different attributes in a form. Springs implementation of RequestDataValueProcessor (CsrfRequestDataValueProcessor) actually does all the work. The ```<csrf />``` makes a bean with the CsrfRequestDataValueProcessor.

**Comment by ncrum** [comment]
@phillipuniverse I got the admin to now use sec:csrf in the latest commits
However, there are a few issues to be fixed:
* [ ] Fix issue of /admin causing 500 error and not redirecting to login before login
* [ ] Fix issue of CSS for logout button now that it is a `form/input` instead of `a[href]`

Those are next on my list to fix. After that I will tackle expanding this to DemoSitePrivate.

**Comment by ncrum** [comment]
@phillipuniverse @bpolster if you want to check this out when you get a chance.
I implemented the rest of the new csrf stuff. I also address the multipart case and from my testing it works. I did this for demosite private and enterprise as well. From my personal testing, it works.

**Comment by ncrum** [comment]
updated BLC.js for ajax calls... only getCsrfToken needs to be updated to get the correct name '_csrf' instead of the old 'csrfToken'

**Comment by ncrum** [comment]
@phillipuniverse I updated the `BLC.js` to use the meta-data csrf first, as well as adding the csrf token to the meta-data for `DemoSite` and `DemoSitePrivate`. Below is an example of it using the meta-data csrf token.

![](http://cl.ly/image/1J2W3I0S1j3f/Image%202015-04-13%20at%204.18.48%20PM.png)

As you can see the `getCsrfToken` function allows backwards compatibility with the old csrfToken filtering. Also it looks for the token within an input field in case the client didn't update their meta-data.

**Comment by ncrum** [comment]
Tested on `DemoSite` for `site` and `admin`. 
Tested on `DemoSitePrivate` for `site` and `admin`.

**Comment by ncrum** [comment]
Doing research into automating csrf query parameter to `multipart` forms...
