### ISSUE TITLE
New approach to module configuration

### ISSUE THREAD

**Issue by charchar** [BroadleafCommerce/BroadleafCommerce#1185]
The goal here is to get web.xml to automatically pick up all modules for a project, without having to add applicationContext.xml files to the list of patchConfigs.

The approach we are taking is to create reference files of the applicationContexts and put these files in resources/blc-config/admin (and resources/blc-config/site) for all modules.  Then we will grab all of these files from web.xml using something like: `classpath*:/blc-config/admin/bl-*-applicationContext.xml`

**Comment by phillipuniverse** [comment]
@charchar is there anything left on this? Can this be closed?

**Comment by charchar** [comment]
@phillipuniverse The Multi-Tenant modules were refactored to use this format, but not any other modules.  Not sure if others should be converted as well.

**Comment by phillipuniverse** [comment]
Will take the others on a case-by-case basis.
