### ISSUE TITLE
Admin - Upload Asset does not function in 3.1.10-GA on IE 8,9, and 10

### ISSUE THREAD

**Issue by vivekjuneja** [BroadleafCommerce/BroadleafCommerce#1197]
We found that on the current version 3.1.11-SNAPSHOT / 3.1.10-GA, Upload Asset function Does NOT work for BLC Admin.

We found that there is NO Network call that is issued when the “Upload Asset” button is clicked, and an Image is selected.

On IE 11 and other browsers – Chrome, Firefox etc, this problem does NOT exist, and Upload Asset works properly. 

Steps to reproduce the issue ->
1. Access BLC Admin Console
2. Go to “Media Assets” under Content Section
3. Click on “Upload Asset” and upload an Image
4. Check if the Image is uploaded and the user is presented with the Form where Title and Alt Text needs to be filled.

On selecting the image from the File Browser, the Image does NOT get uploaded, and the form doesn't appear. The user remains on the /admin/assets page. 

We checked the BLC Admin Console on IE 8,9,10 using http://www.browserstack.com and Windows 7 Environment.

**Comment by vivekjuneja** [comment]
@brundonsmith - I have issued a Pull Request on the "BroadleafCommerce-3.1.x" to remove the onpropertychange attribute. As mentioned I had performed testing on the given browsers.

**Comment by brundonsmith** [comment]
@vivekjuneja - I apologize, this slipped off my radar for a while. The onpropertychange attribute was placed there so that the form would submit as soon as the file is selected. Are you saying that it submits automatically even without the event listener?

**Comment by vivekjuneja** [comment]
@brundonsmith - Thanks !  Are you planning to cut out a release for this ?

**Comment by bpolster** [comment]
@phillipuniverse Please assign to next release.

**Comment by phillipuniverse** [comment]
This will be in the 3.1.11-GA release.
