### ISSUE TITLE
blc:src adds duplicate contextPath

### ISSUE THREAD

**Issue by ArloL** [BroadleafCommerce/BroadleafCommerce#1208]
When converting th:src to blc:src I have noticed that it duplicates the context path.

E.g. `@{/img1.jpg}` becomes `/service-shop/service-shop/img1.jpg` instead of `/service-shop/img1.jpg`.

It is first added in [UrlRewriteProcessor:93](https://github.com/BroadleafCommerce/BroadleafCommerce/blob/764f5d48700af0f19eed73b5c79a33533ecc03e1/admin/broadleaf-contentmanagement-module/src/main/java/org/broadleafcommerce/cms/web/processor/UrlRewriteProcessor.java#L93) when evaluating `@{}` and again in [StaticAssetPathServiceImpl:169](https://github.com/BroadleafCommerce/BroadleafCommerce/blob/764f5d48700af0f19eed73b5c79a33533ecc03e1/common/src/main/java/org/broadleafcommerce/common/file/service/StaticAssetPathServiceImpl.java#L169).

**Comment by phillipuniverse** [comment]
Thanks, definite bug.

Assuming that you're on 3.1.x?

**Comment by ArloL** [comment]
Yes, 3.1.10-GA.

**Comment by phillipuniverse** [comment]
This was a regression from #1111. Thanks again for the report @ArloL
