### ISSUE TITLE
Remove Solr warning message on embedded Solr startup

### ISSUE THREAD

**Issue by broadleaf-infrastructure** [BroadleafCommerce/BroadleafCommerce#1216]
Currently when you start up with embedded Solr you get a log message that looks like this:

```shell
[ WARN] 11:11:57 SolrResourceLoader - Can't find (or read) directory to add to classloader: lib (resolved as: /var/folders/dr/lp2fx18n3lq8hbrjx2k6vf500000gp/T/someuser/solrhome/lib).
```

This is harmless, but it is caused by the `sharedLib=lib` property of `solr-default.xml` (which becomes `solr.xml` in solrhome). In the provisioning of Solr home with embedded Solr, we never actually create the lib directory. This doesn't really matter because in the current implementation we aren't using any jars in the lib directory.

If we actually create the lib directory inside of solrhome, we get a slightly different warning:

```shell
[ WARN] 11:11:57 SolrResourceLoader - No files added to classloader from lib
```

On startup, Solr just wants to verify that there is some file (any file) inside of lib. I think that the right answer here is to create the lib directory and then a temporary file inside of that. That will give the added benefit of being able to move the embedded index to some other environment after using it as a starting point for building out the lib directory with other Solr features.

**Comment by phillipuniverse** [comment]
Whoops, logged into the wrong user account there.

**Comment by phillipuniverse** [comment]
Re-opening to backport to 3.1.12
