### ISSUE TITLE
Add to cart not finding customer ID

### ISSUE THREAD

**Issue by brundonsmith** [BroadleafCommerce/BroadleafCommerce#1231]
When using the endpoint "/cart/{categoryId}/{productId}/{skuId}: POST" with the query parameter "?customerId=100", I'm getting a 404 and the following on the console:
```
[artifact:mvn] [ WARN] 12:58:52 CartStateRequestProcessor - No customer was found on the current request, no cart will be added to the current request. Ensure that the blCustomerStateFilter occurs prior to the blCartStateFilter
```

It's possible that there's something wrong with the workflow as the message suggests, or it's possible that the docs are wrong. They say "NOTE: The customer ID must be passed on each request. It can be passed on a query parameter or a request header. But it must be keyed by customerId."

**Comment by phillipuniverse** [comment]
In this case the docs are wrong. There is no longer a method for `/cart/{categoryId}/{productId}`, instead it is just `/cart/{productId}` from looking at the `CartEndpoint` in the DemoSite.

Not sure if there is a great reason why that method was removed in the first place. I also opened up BroadleafCommerce/docs#53 to investigate other areas that might be wrong.
