### ISSUE TITLE
Rest API 500 errors returning HTML response

### ISSUE THREAD

**Issue by brundonsmith** [BroadleafCommerce/BroadleafCommerce#1232]
500 errors made to the Rest API are supposed to return an appropriate json/xml error response. Instead, they seem to be returning HTML error pages. I'm not positive whether this is the case for all 500 errors or only some (or one), but one URL that definitely does this is /api/v1/cart?customerId=X, where X is a customer ID that doesn't exist.

**Comment by phillipuniverse** [comment]
Looks like this only occurs if you pass in a non-number in as a customerId. I tested the other cases against that method like a GET against `api/v1/cart?2332431` and it returns a 404 not found correctly parsed in XML/JSON.

If I were to instead actually literally invoke `/api/v1/cart?customerId=X` or `/api/v2/cart?customerId=somegarbledygoopnotanumber` then I would get an html-like page because that exception occurred in the servlet filter.

**Comment by brundonsmith** [comment]
This is happening for me even when customerId is a number.

**Comment by phillipuniverse** [comment]
What's the specific number you're using along with header information and method (POST vs GET vs PUT etc)? And what is the actual response output that you get back?

**Comment by brundonsmith** [comment]
![untitled](https://cloud.githubusercontent.com/assets/3674979/5877832/1c0375b8-a2e8-11e4-85d1-d5430700bd42.png)

**Comment by phillipuniverse** [comment]
This was caused by missing these 2 beans in `applicationContext-rest-api.xml`:

```xml
<!-- This adds (optional) support for serializing and deserializing Broadleaf extensions.  This can be commented out, especially if specifying 
     custom endpoint method signatures. If you've extended BLC API wrapper classes, then class does it's best to serialize the right information.  
     Deserialization does not always work, especially when polymorphic possibilities are involved.  In these cases, it is best to explicitly provide 
     specific method signatures (URIs) for each polymorphic type that will be deserialized.
     This MUST be marked as singleton. -->
<bean class="org.broadleafcommerce.core.web.api.BroadleafMessageBodyReaderWriter" scope="singleton"/>

<!-- This generic JAX-RS exception mapper can be commented out, and/or can be replaced with a custom 
     exception mapper or mappers.
     This MUST be marked as singleton. -->
<bean class="org.broadleafcommerce.core.web.api.BroadleafRestExceptionMapper" scope="singleton"/>
```

These are not automatically component scanned in Broadleaf 3.1 and there was no mention of them in the REST API setup docs.
