### ISSUE TITLE
Images not being returned for a product

### ISSUE THREAD

**Issue by xdhmoore** [BroadleafCommerce/BroadleafCommerce#1236]
I'm having trouble getting images back for a product:

1. I add a media item (image file) to a product via the admin screen
2. The media item shows up on the admin Media tab
3. I can hit the image url in the browser directly and it returns the image
4. When I call `product.getMedia()` on the same product, it returns an empty map.

Stepping into `getMedia()`, after a couple steps it calls `SkuImpl.getSkuMediaXref()`.  In the debugger I can see `skuMedia` has the media image in it, but then the `skuMedia.isEmpty()` returns true, because of the logic in `WorkflowPersistentMap.isEmpty()`.  Idk.  Maybe a wild goose chase.

Also, it appears that in our DB, when we add images, the `BLC_MEDIA` table gets 2 new rows.  1 row has `ARCHIVE` set to `Y` and this is the row that `BLC_SKU_MEDIA_MAP` appears to be referencing via `MEDIA_ID`.  I thought that this might be part of the problem.

**Comment by bpolster** [comment]
@xdhmoore  What version are you seeing this error?

**Comment by xdhmoore** [comment]
broadleaf-enterprise-1.1.0-ALPHA-ENT-31

**Comment by xdhmoore** [comment]
```xml
<properties>
        <blc.version>3.2.0-ALPHA-ENT-30</blc.version>
        <broadleaf-menu.version>1.0.0-RC1</broadleaf-menu.version>
        <broadleaf-theme.version>1.5.0-RC1</broadleaf-theme.version>
        <broadleaf-custom-field.version>1.2.0-ALPHA-ENT-30</broadleaf-custom-field.version>
        <broadleaf-advanced-cms.version>1.5.0-RC1</broadleaf-advanced-cms.version>
        <broadleaf-common-modules-enterprise.version>2.0.0-RC1</broadleaf-common-modules-enterprise.version>
        <broadleaf-jobs-events.version>1.1.0-RC1</broadleaf-jobs-events.version>
        <broadleaf-enterprise.version>1.1.0-ALPHA-ENT-31</broadleaf-enterprise.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
	</properties>
```

**Comment by xdhmoore** [comment]
It's very possible we have something set up wrong, but we're having a lot of trouble determining what it is.

**Comment by xdhmoore** [comment]
To clarify on my 2nd paragraph above, It appears that `WorkflowPersistentMap.entrySet()` is returning an empty map when it is called by `SkuImpl.getSkuMedia()`, even though the parent class' map has values in it.

**Comment by bpolster** [comment]
Ok, looks like this is an enterprise issue.   Can you send an email to support@broadleafcommerce.com?    We'll need to track that outside the community issues.   You can reference this ticket.

**Comment by xdhmoore** [comment]
@bpolster, sure, thanks.

**Comment by bpolster** [comment]
Tracked at https://github.com/BroadleafCommerce/QA/issues/226

**Comment by bpolster** [comment]
Client reported that the image had not yet been promoted.
