### ISSUE TITLE
CartStateFilter called multiple times in a request breaks order locks

### ISSUE THREAD

**Issue by smmckay** [BroadleafCommerce/BroadleafCommerce#1239]
CartStateFilter can be called multiple times in a single request, e.g. during an internal forward. With DatabaseOrderLockManager the result is an exception on the attempt to re-acquire the lock.

**Comment by phillipuniverse** [comment]
Seems like the fix is to have `CartStateFilter` extend from Spring's `OncePerRequestFilter` (which all of the out-of-the-box Spring Security filters extend from)

**Comment by smmckay** [comment]
I expect so, and what I've done as a workaround is extend CartStateFilter to function similarly. Seems to work fine.
