### ISSUE TITLE
AdminUserCustomPersistenceHandler saves admin user too aggressively, especially when another entity tries to create a relationship to it

### ISSUE THREAD

**Issue by ktisdell** [BroadleafCommerce/BroadleafCommerce#1240]
This causes validation to occur, even if the AdminUser is not being saved.

The ```canHandleAdd``` method should inspect the ```persistencePackage``` to ensure that no sectional crumbs exist.

**Comment by ktisdell** [comment]
Per @jefffischer I evaluated the persistencePackage to ensure that the persistencePerspectiveItems are empty rather than checking the crumbs:

```
persistencePackage.getPersistencePerspectiveItems().isEmpty();
```

**Comment by ktisdell** [comment]
The above commit fixed this specific issue.

**Comment by phillipuniverse** [comment]
@ktisdell what annotation was on the `@ManyToMany`? `@AdminPresentationAdornedTargetCollection`?

**Comment by ktisdell** [comment]
```@AdminPresentationCollection```
