### ISSUE TITLE
Upgrade CustomerService and AdminSecurityService to use new Spring Security 3.2+ PasswordEncoder

### ISSUE THREAD

**Issue by elbertbautista** [BroadleafCommerce/BroadleafCommerce#1248]
As of Spring Security 3.1.4.RELEASE, the old org.springframework.security.authentication.encoding.PasswordEncoder has been deprecated in favour of org.springframework.security.crypto.password.PasswordEncoder.

The new interface PasswordEncoder is recommended in order to better accommodate the best practice of randomly generated salt that is included with the password.
See: https://jira.spring.io/browse/SEC-2147

**Comment by phillipuniverse** [comment]
@elbertbautista FYI this will likely break every implementation that is using the primary key for a salt.

**Comment by bpolster** [comment]
maintain both as a configurable strategy

**Comment by pbaggett** [comment]
Closing as duplicate of BroadleafCommerce/BroadleafCommerce#1288
