### ISSUE TITLE
NullOrderImpl should not use static Money.ZERO in getSubTotal() 

### ISSUE THREAD

**Issue by elbertbautista** [BroadleafCommerce/BroadleafCommerce#1256]
NullOrderImpl should not use static Money.ZERO in getSubTotal() as it is always initialized with the system default currency and doesn't take into account the default currency that may be set on the request context.

return new Money(BigDecimal.ZERO) instead

**Comment by phillipuniverse** [comment]
As Elbert and I were talking about it, I think that this calls into question ALL usage of `Money.ZERO`. The problem is that every time you say `Money.ZERO` you will get Money back that is in the default system currency no matter what is on the `BroadleafRequestContext`.

**Comment by phillipuniverse** [comment]
Re-opening this for the time being I want to take a closer look.
