### ISSUE TITLE
Provide support for more comprehensive manipulation of resource paths based on site information

### ISSUE THREAD

**Issue by jefffischer** [BroadleafCommerce/BroadleafCommerce#1268]
The needs of the multitenant module are such that better support for manipulating resource paths based on site information needs to be provided.

**Comment by phillipuniverse** [comment]
@jefffischer doesn't something similar to this need to happen in `FileSystemFileServiceProvider`? IT uses a similar idea to put `Site` within the context of a file path

**Comment by jefffischer** [comment]
@phillipuniverse depends on whether or not the resources created using this service for a template site need to be rendered as well on a template site. Do you know the use case in which this provider is engaged?

**Comment by phillipuniverse** [comment]
It's the default use case of where the final result of files go to live. Everything flows through `BroadleafFileService` which maintains a list of providers. The `FileSystemFileServiceProvider` is the one that is hooked up by default and utilizes `asset.server.file.system.path`.

As a general concept though, there are other file providers that also would need the same sort of logic (Amazon S3, Rackspace Cloud Files that do the same sort of thing just remotely).

**Comment by jefffischer** [comment]
I agree. BroadleafFileService first looks locallly via getLocalResource (this is what I changed). If not found, it goes to getResource, which delegates to the defaultFileServiceProvider for retrieval. FileSystemFileServiceProvider, in this case, would need to be able to benefit from the same extension as BaseFileService.

**Comment by jefffischer** [comment]
New separate issues have been opened for S3 and RackSpace.

**Comment by jefffischer** [comment]
This still needs some work
