### ISSUE TITLE
Filtering media assets by url doesn't work, main search function doesn't work either

### ISSUE THREAD

**Issue by Pr0TuX** [BroadleafCommerce/BroadleafCommerce#1269]
**Broadleaf Framework** : 3.1.8-GA
**Admin demo project** : 3.1.8-GA

**Steps to reproduce**

1.) Go to admin
2.) Select a ``Content``
3.) Select ``Media Assets`` tab
4.) Try to filter by 'URL', by pressing the header 
5.) Popup appears

**Expected result** :  This popup should contain some input so that user is able to enter url to filter for.
**Actual result** :  Popup appears but there is no input, so user doesn't have the possibility to filter by url. Also if you enter ``/admin/assets?fullUrl=asd`` for sorting by using url parameter it doesn't work.

**Note** There is a problem also with main filter capability, because it tries to filter by using the first header column which is a virtual one representing only a thumbnail of the asset. Here you could either change this column to be last? or second, so main filtering should use first column which is ``Name`` of the asset.

**Comment by Pr0TuX** [comment]
One simple idea would be to extend ``org.broadleafcommerce.openadmin.server.service.persistence.module.provider.BasicFieldPersistenceProvider#canHandleSearchMapping`` adding condition that it can handle ``SupportedFieldType.ASSET_URL`` also and change ``broadleaf-open-admin-platform-3.1.8-GA.jar!/open_admin_style/templates/fields/filter/asset_url.html`` to contain something like ``broadleaf-open-admin-platform-3.1.8-GA.jar!/open_admin_style/templates/fields/filter/string.html`` contains.

```
<input th:attr="data-name=${fieldName}"
	   th:placeholder="#{${fieldFriendlyName}}"
	   class="listgrid-criteria-input"
	   type="text" />
```

**Comment by phillipuniverse** [comment]
Yup, great idea that fixed it. Sorry for the late response here, this will be in the 3.1.14-GA build.
