### ISSUE TITLE
Deprecate the use of an extra defaultCategory property on Product and Category in favor of maintaining the relationship list

### ISSUE THREAD

**Issue by jefffischer** [BroadleafCommerce/BroadleafCommerce#1287]
Currently both Product and Category have the concept of a defaultCategory in addition to a separate list containing all possible parent categories. The defaultCategory is important for a number of pieces of functionality, including breadcrumbs. The list is important for driving queries to detect catalog membership and hierarchy, etc.. It has been difficult to rectify these two parent category usage patterns in a consistent way. Therefore, the purpose of this refactor is to deprecate defaultCategory and the list of parent categories and go to a single parent model that covers all usages. Here are the touch points:

1. Deprecate defaultCategory on Product and Category.
2. Deprecate the mutators for allParentCategoryXrefs on Product and Category. This list field is being re-purposed.
3. Introduce a new parentCategory concept on Product and Category that represents the single parent category. The new parentCategory concept is housed in the allParentCategoryXrefs list.
4. The parentCategory field is displayed in the admin as a Category lookup and the defaultCategory field and the parent categories list grid are removed from the admin ui.
5. By setting "use.legacy.default.category.mode=true" in the implementation's property file, the implementation can go into a legacy support mode in which the functionality is returned to a state similar to that of 3.1. In legacy mode:
   - The defaultCategory field is returned to the admin ui and the mutators on Product and Category operate the same as they did before.
   - The parent categories list grid is returned to the admin ui and the mutators on Product and Category operate the same as they did before.

When legacy mode is false (the default), calls to getDefaultCategory have been altered to return the new parentCategory concept. However, if a defaultCategory value already exists, it will be honored for calls to the deprecated getDefaultCategory method.

**Comment by ckittrell** [comment]
@jefffischer Should `isDefaultCategoryLegacyMode()` return false if `BroadleafRequestContext.getBroadleafRequestContext().getAdditionalProperties().get(BroadleafAdminRequestProcessor.USE_LEGACY_DEFAULT_CATEGORY_MODE)` returns null? Also, where is `use.legacy.default.category.mode` supposed to be set? `isDefaultCategoryLegacyMode()` is always returning `null` in `ProductCustomPersistenceHandler` for DemoSitePrivate which causes an NPE when attempting promotion.

**Comment by jefffischer** [comment]
I think you must be missing some recent code. In the enterprise module, the legacy mode is set on the request context in the promotion event consumer.

**Comment by ckittrell** [comment]
That was it exactly. I was in the `develop-2.1.x` Enterprise branch which wasn't up-to-date.

**Comment by phillipuniverse** [comment]
Re-opened to capture additional conversations from a meeting with @bpolster @jefffischer and I. New action items:

- Undo the deprecation the list of parent categories for a Product (e.g. products should still be allowed to be members of multiple categories)
- Undo the deprecation the idea that a category can have multiple parents. This can prevent having to duplicate a hierarchy from the cateory tree and the menu tree
- Keep the deprecation on the defaultParentCategory property on both Product and Category
- Add a new property to the join between Category <-> Product and Category <-> Category that delineates that relationship being "default" **(is there another term for this other than 'default' that we could use? Maybe 'Use In Main Hierarchy' with some help text that mentions it will be apart of canonical URLS and in the case of Products it can inherit fulfillment type, inventory type, etc?)**
- Keep the single-displayed property on Category and Product that will actually modify elements in that list. This is how it works now except that it will modify whichever one is the 'default'. It should look through the categories that it is related to, remove the one that it is already marked as 'default' and set the new one equal to it. If that relationship is already there (e.g. I'm already related to `cat2` and I set `cat2` as my parent through the property) then in the admin we should find that and just set the property on that relationship.

#### New Admin UI constraints:
- In the new UI of the admin whenever you move a category to another then you are modifying the *relationship* and nothing else. If that relationship happened to be a 'default' relationship then wherever you moved it becomes the new default
- Investigate how to differentiate for adding a brand new category vs. hooking up a relationship. The answer here might be that we don't provide the management capabilities in the admin to particularly add new relationships outside of the hierarchical 'default' concept but our domain model and some UI functionality still supports it


#### Migrating
1. Add a new column
2. Move the foreign keys set in defaultParentCategory and set them in the correct join table with the 'default' (or whatever it will be called) property set to true

**Comment by phillipuniverse** [comment]
@jefffischer do you think it still makes sense to even have the pseudo-property at all? What if someone were to simply manage it as an adorned target property on the relationship between Product -> Category?

Also, in `CategoryCustomPersistenceHandler` and `ProductCustomPersistenceHandler` it looks like we're still hiding the xref parent lists in the inspect. These should be shown, right?

**Comment by jefffischer** [comment]
The pseudo property makes sense from the perspective of the user experience. It is desirable to manage the parent category as a ToOn lookup on the main form. Also, my understanding is that the allParentCategories collection is supposed to be hidden on the product/category form. While the API is still available on the entity, we don't really want people assigning additional parent categories from the child side. If you want to add more non-default children, you can do so from the parent side.

**Comment by phillipuniverse** [comment]
Makes sense about the lookup property on the main form from a UX perspective.

Why don't we want people assigning parent categories from the child side? If we now are back to saying that we fully endorse child-side lookups in the API (give me all the parent categories that I am apart of) I can't think of a reason that we would explicitly disable that in the admin. If I'm looking at a product, I would want to see if I'm apart of Hot-Sauces and Clearance. Otherwise I have to hunt through each category to see if the product that I care about is in the list of children.

**Comment by bpolster** [comment]
We are trying to simplify the UX.      We are no longer going to support multiple-parent category relationships and want to remove that from the UI.      For products, its not as big of a concern to me if we show the "all parent categories".     There can be some confusion on what is going on with the "default" which is also part of that list.    Also, when adding from the product side, you aren't specifying the order that the product exists in that category.   

That said, showing the all parent categories from the product side is ok (assuming it works).

**Comment by jefffischer** [comment]
If it's interesting to see the categories to which a product belongs, I think about the best we could do is make the allParentCategories grid visible on product and make it read only. This is because the first thing that is done when you edit the parent category field is revert any user sandbox edits to allParentCategories. This keeps compounding changes from building up in the user sandbox for maintaining parent category. However, this would have a confusing side effects for a user that edited the allParentCategories list grid and the parent category field, because the edit(s) to the allParentCategories list grid would "magically" disappear.

**Comment by jefffischer** [comment]
I'm going to leave this open and target it for 4.0.1. Changing the product.allParentCategoriesXref admin presentation annotation to read only seems to work, but more testing needs to be done. Additionally, the read only grid displays a single "view" button, presumably to see a pop-up of the category detail. However, this throws a NPE. This itself may result in a different 4.0.1 bug.
