### ISSUE TITLE
Forgot password support uses deprecated PasswordEncoder

### ISSUE THREAD

**Issue by smmckay** [BroadleafCommerce/BroadleafCommerce#1288]
`org.springframework.security.authentication.encoding.PasswordEncoder` is deprecated in Spring Security 3.2. Its replacement, `org.springframework.security.crypto.password.PasswordEncoder`, doesn't accept a salt parameter, viz. it exists to support bcrypt. This makes it unusable in the forgot password scenario, because running the token through bcrypt twice will produce two different hashes.

Okay, the reason for salt is that users pick terrible passwords that are easily bruted. This isn't a problem for password reset tokens because users don't pick them. Hashing with SHA-256 or another decent algorithm is sufficient.

P.S. The real problem is that Broadleaf is depending on the deprecated PasswordEncoder. The real solution would be to replace blPasswordEncoder with the new implementation. The issue I'm reporting is just the first I've run into that doesn't have a decent workaround.

**Comment by smmckay** [comment]
Reporting against the develop branch BTW.

**Comment by phillipuniverse** [comment]
@smmckay we are working on a couple of changes here:

1. Fix the current bug with the now-deprecated password encoder that uses the API incorrectly (it should be using `isPasswordValid()` anyway rather than re-encrypting the token)
2. Add in native support for the new `PasswordEncoder` interface while maintaining support for the existing `PasswordEncoder` to reduce the required migration steps while deprecating methods and uses that we shouldn't continue to try to support
3. Default the production-recommended implementation to BCrypt and new implementations to use encoders within the recommended `PasswordEncoder` interface

Thanks for the bringing this to our attention.

**Comment by phillipuniverse** [comment]
@smmckay the above commits fix your issue. We are no longer re-hashing the password when verifying the token and are instead using `isPasswordValid()` (in both the new and old API).

Furthermore, the change that @pbaggett made above allows both the new and old password encoders to function properly by looking at the type of `blPasswordEncoder` (or `blAdminPasswordEncoder`) and casting it correctly depending on the type. People that are currently using the deprecated interface for `PasswordEncoder` won't break but you still have the opportunity to use the new `PasswordEncoder` interface (like to use Spring's OOB `org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder` class).

Let us know if you still have issues and as always thanks for the great issue reporting!

**Comment by smmckay** [comment]
Oh yeah, I remembered why I used SHA-256: so `CustomerForgotPasswordSecurityTokenDaoImpl.readToken` would keep working. It doesn't now, if you use a new password encoder. Scanning a user's reset tokens would work.

**Comment by pbaggett** [comment]
@smmckay Correct, `CustomerForgotPasswordSecurityTokenDaoImpl.readUnusedTokensByCustomerId` should be used now in conjunction with `PasswordEncoder.matches` to find the correct token. `CustomerServiceImpl.checkPasswordResetToken` has been updated to reflect this change.

Similarly, in the admin side, `ForgotPasswordSecurityTokenDao.readUnusedTokensByAdminUserId` should be used and `AdminSecurityServiceImpl.resetPasswordUsingToken` has been updated to reflect this.

**Comment by pbaggett** [comment]
As mentioned in the original description, it breaks the contract of the new password encoder to call `encode` twice on the same input and expect the two hashes to be equal. Therefore, it's impossible to get the correct token when using `CustomerForgotPasswordSecurityTokenDaoImpl.readToken` and the new password encoder.

**Comment by smmckay** [comment]
Oh dang, my reset form is broken and I didn't check it thoroughly enough. Sorry to waste your time.
