### ISSUE TITLE
Provide a mechanism that can be used to keep track of current state information for a local Solr index

### ISSUE THREAD

**Issue by jefffischer** [BroadleafCommerce/BroadleafCommerce#1309]
This mechanism is primarily used when dealing with embedded Solr.

1. A generic IndexStatusInfo object keeps track of last processed date and arbitrary additional information about the Solr index.
2. A SolrIndexStatusProvider is responsible for managing status. The default implementation is FileSystemSolrIndexStatusProviderImpl, which maintains the index status information on disk.
3. A SolrIndexStatusService is responsible for using any and all providers for maintaining the index status.

The enterprise codebase makes use of this mechanism during solr index event consumption.

**Comment by phillipuniverse** [comment]
The current implementation of this depends on embedded Solr and throws an exception when using standalone Solr because there is no `solrHomePath` set on the `SolrSearchService`.

**Comment by phillipuniverse** [comment]
I should also note that even though this was intended for embedded Solr it is running with standalone Solr as well which is really the problem. From the description this whole thing should probably be disabled for standalone.

**Comment by jefffischer** [comment]
@phillipuniverse Can you please post the exception?

**Comment by pbaggett** [comment]
```
[artifact:mvn] [TRACE] 16:27:56 WorkflowSolrIndexServiceImpl - Executing delete query productId:(-2060) AND (sandboxId:("53" 0)) AND catalog_s:("-3" )
[artifact:mvn] [ERROR] 16:27:56 SolrDocInvalidationEventConsumer - Unable to invalidate Solr doc
[artifact:mvn] java.lang.NullPointerException
[artifact:mvn] 	at java.io.File.<init>(File.java:277)
[artifact:mvn] 	at org.broadleafcommerce.core.search.service.solr.FileSystemSolrIndexStatusProviderImpl.handleUpdateIndexStatus(FileSystemSolrIndexStatusProviderImpl.java:77)
[artifact:mvn] 	at org.broadleafcommerce.core.search.service.solr.SolrIndexStatusServiceImpl.setIndexStatus(SolrIndexStatusServiceImpl.java:40)
[artifact:mvn] 	at com.broadleafcommerce.enterprise.workflow.site.service.event.consumer.SolrDocInvalidationEventConsumer$1.execute(SolrDocInvalidationEventConsumer.java:85)
[artifact:mvn] 	at org.broadleafcommerce.common.util.StreamingTransactionCapableUtil.runOptionalTransactionalOperation(StreamingTransactionCapableUtil.java:140)
[artifact:mvn] 	at org.broadleafcommerce.common.util.StreamingTransactionCapableUtil.runTransactionalOperation(StreamingTransactionCapableUtil.java:113)
[artifact:mvn] 	at org.broadleafcommerce.common.util.StreamingTransactionCapableUtil.runTransactionalOperation(StreamingTransactionCapableUtil.java:107)
[artifact:mvn] 	at com.broadleafcommerce.enterprise.workflow.site.service.event.consumer.SolrDocInvalidationEventConsumer.consumeEvent(SolrDocInvalidationEventConsumer.java:69)
[artifact:mvn] 	at com.broadleafcommerce.jobsevents.service.DatabaseSystemEventNodeImpl.executeEvent(DatabaseSystemEventNodeImpl.java:278)
[artifact:mvn] 	at com.broadleafcommerce.jobsevents.service.DatabaseSystemEventNodeImpl$ConsumeJob$3$1$1.run(DatabaseSystemEventNodeImpl.java:430)
[artifact:mvn] 	at java.lang.Thread.run(Thread.java:745)
```

**Comment by jefffischer** [comment]
Re-closing this issue. This is actually a bug from the enterprise side. I will re-open and address the issue in QA.

**Comment by phillipuniverse** [comment]
This was still causing startup exceptions for me. The above fix removes any reliance on the embedded `solrhome` property that never gets set if you're using standalone Solr.
