### ISSUE TITLE
For rules to Pages and Content Items specific for certain times, filter values aren't displayed.

### ISSUE THREAD

**Issue by Pr0TuX** [BroadleafCommerce/BroadleafCommerce#1326]
**Broadleaf Framework** : 3.1.12-GA
**Admin demo project** : 3.1.12-GA

**Steps to reproduce**

1.) Admin → Content → Pages/ Content Items → tab Rules
2.) Select "Restrict to certain times?" → is equal to (in not equal to)

**Expected result** :  An empty field is listed to enter your values.
**Actual result** :  No field is listed.

**Comment by phillipuniverse** [comment]
This appears to all be working as designed depending on the fields themselves:

![screen shot 2015-05-21 at 11 40 45 am](https://cloud.githubusercontent.com/assets/684275/7753943/4deb57b2-ffae-11e4-96f7-f89821b26415.png)
