### ISSUE TITLE
When adding an extend Sku, admin doesn't allows possibility to select product option values.

### ISSUE THREAD

**Issue by Pr0TuX** [BroadleafCommerce/BroadleafCommerce#1327]
**Broadleaf Framework** : 3.1.12-GA
**Admin demo project** : 3.1.12-GA

**Development Story**
We need to extend ``org.broadleafcommerce.core.catalog.domain.SkuImpl``, we also use ``org.broadleafcommerce.common.presentation.AdminPresentationClass`` so that we force admin to always instantiate and use our extended sku, let's call it  ``ExtSkuImpl``

1.) Go to ``Products``
2.) Select ``Product Options``
3.) Select ``Additional Skus``, ``Add`` button

**Expected result** : Popup appears and user has the possibility to select product option values for products options.

**Actual result** :    Popup appears but user hasn't the possibility to select product option values (although the product has COLOR and SIZE as product options set, for edit it works)

**Note** :  One solution is to extend ``org.broadleafcommerce.admin.server.service.handler.SkuCustomPersistenceHandler`` and to change 

``org.broadleafcommerce.admin.server.service.handler.SkuCustomPersistenceHandler#createIndividualOptionField`` 
``org.broadleafcommerce.admin.server.service.handler.SkuCustomPersistenceHandler#getBlankConsolidatedOptionProperty`` 
``org.broadleafcommerce.admin.server.service.handler.SkuCustomPersistenceHandler#getConsolidatedOptionProperty``
``org.broadleafcommerce.admin.server.service.handler.SkuCustomPersistenceHandler#createConsolidatedOptionField``

the problem is that all this methods are static methods, and user hasn't the possibility to change them in order to add extra ``setAvailableToTypes`` for ``org.broadleafcommerce.openadmin.dto.BasicFieldMetadata`` like ``ExtSkuImpl``.

One simple solution would be to make this methods ``protected/public`` but not ``static`` so we have the possibility to change them, or add an extension point.

**Note2** also filtering and sorting by ``consolidatedProductOptions`` and it seems normal, because it is a generate column. Suggestion, make this column as no filter and sort capable.

**Comment by phillipuniverse** [comment]
FYI the main problem here is the list contained in the `availableToType`. It should either contain the subclasses as well or the `FormBuilderService` method that removes non-applicable fields (like the `skuBundleItems` list from appearing on a `Product`) should be smart enough to handle subclasses as well.

**Comment by phillipuniverse** [comment]
Fix was to include subclasses in the availableToTypes when manually building the product option field metadata.
