### ISSUE TITLE
sessionTimer.js logs out valid session

### ISSUE THREAD

**Issue by smmckay** [BroadleafCommerce/BroadleafCommerce#1335]
When I go to /product, the page initially displays and then redirects to login. Client-side I'm not really able to debug due to the redirect wiping out the browser's logs. However, from the server's perspective this is what happens:

1. Request to /sessionTimerReset
2. Cookie is set with name sessionResetTime and path */product* (due to running in a root servlet context). This I managed to see before the redirect.
3. Request to /adminLogout.htm
4. Request to /login

Also somewhere in there is an auth failure from an anonymous request to /product. Maybe after the logout request?

**Comment by phillipuniverse** [comment]
Thanks @smmckay we're looking at this one today.

**Comment by ncrum** [comment]
@smmckay thanks for pointing this out. I'm taking a look at this right now.
I tried to recreate this using both Chrome and Firefox locally to no avail.
If you don't mind, I have a few questions to try to figure out what happened:

1. I assume based on your notes this is on the `admin` site.
2. Which browser are you using? 
3. Does this happen every time you go to `localhost:8081/admin/product`?
4. The cookie should be set to the path `/admin`, which should be the servletContext, is yours being set to `/product`?
5. Did you start this up using `ant tomcat` first for `site`, then for `admin`?

Thanks again for the feedback, we'll get this fixed soon.

**Comment by smmckay** [comment]
Browser is Safari on OS X Yosemite. I'm running Broadleaf embedded and in the root servlet context, so client-side `BLC.servletContext === ''`. Startup is bespoke.

**Comment by ncrum** [comment]
Ah, so you modified `admin/pom.xml` to have the root servlet context.
I just attempted the same setup by doing...
```
...

<finalName>ROOT</finalName>

...

<groupId>org.apache.tomcat.maven</groupId>
 <artifactId>tomcat7-maven-plugin</artifactId>
 <configuration>
  <path>/</path>
  <port>${httpPort}</port>
  <httpsPort>${httpsPort}</httpsPort>
 </configuration>

...
```

Is this what you have in your pom?

**Comment by ncrum** [comment]
Made some changes to sessionTimer to handle some edge cases that may have caused your bug. 
I updated some of the code to use a specific path value when reading the cookie and also to delete the cookie on invalidation. It's possible the proper cookie wasn't found and timeSinceLastReset had the wrong value making the client think the session had expired, and consequently logging out.

**Comment by ncrum** [comment]
I managed to accidentally recreate this with the `/pages` path. I have a cookie sitting there with the path `/pages` as well. Will look into why this happened.

**Comment by ncrum** [comment]
Deleting that cookie fixes things. And it doesn't seem to recreate it easily.

**Comment by ncrum** [comment]
Can recreate by doing the following:
1. Go to `/pages`
2. Click on About Us page (or any)
3. See a cookie appear for `/pages`

**Comment by ncrum** [comment]
Seems this can be recreated by visiting any `/first_path/secondary_path` then it will create the new `sessionResetTime` cookie on `/first_path`
