### ISSUE TITLE
Unable to delete product - FK constraint

### ISSUE THREAD

**Issue by ckittrell** [BroadleafCommerce/BroadleafCommerce#1343]
Catalog > Products > Sudden Death Sauce -----> Delete

Result:
org.hibernate.exception.ConstraintViolationException: Cannot delete or update a parent row: a foreign key constraint fails (`demosite`.`blc_product`, CONSTRAINT `FK5B95B7C96D386535` FOREIGN KEY (`DEFAULT_SKU_ID`) REFERENCES `BLC_SKU` (`SKU_ID`))

**Comment by phillipuniverse** [comment]
Encapsulated in #842
