### ISSUE TITLE
Unable to delete productOption - FK constraint

### ISSUE THREAD

**Issue by ckittrell** [BroadleafCommerce/BroadleafCommerce#1344]
Catalog > Product Options > Shirt Size -----> Delete

Result:
org.hibernate.exception.ConstraintViolationException: Cannot delete or update a parent row: a foreign key constraint fails (`demosite`.`blc_sku_option_value_xref`, CONSTRAINT `FK7B61DC0BB0C16A73` FOREIGN KEY (`PRODUCT_OPTION_VALUE_ID`) REFERENCES `BLC_PRODUCT_OPTION_VALUE` (`PRODUCT_OPTION_VALUE_ID`))

**Comment by phillipuniverse** [comment]
Encapsulated in #842.
