### ISSUE TITLE
Duplicated functionality for Community - System Properties vs System Property Management

### ISSUE THREAD

**Issue by ckittrell** [BroadleafCommerce/BroadleafCommerce#1347]
Settings > System Properties
vs
Settings > System Property Management

Cause: `Enterprise`'s `AdminSystemPropertyController` causes a different interface to be used for the `System Properties` section

**Comment by bpolster** [comment]
These are different concepts - not duplicates

**Comment by bpolster** [comment]
We may want to hide both by default
