### ISSUE TITLE
URLHandlers never utilize the cache

### ISSUE THREAD

**Issue by phillipuniverse** [BroadleafCommerce/BroadleafCommerce#1348]
On every request we are looping through every single URLHandler and never utilizing the cache. Here's something that is pretty suspect:

```java
protected URLHandler lookupHandlerFromCache(String requestURI)  {
    return checkForMatches(requestURI);
}
```

That method is used whenever we go to check if a URLHandler matches which means that it doesn't utilize the cache like the method says it does.

**Comment by jefffischer** [comment]
The code in this service appears to be working as designed. There is some defunct code in here that deals with a manual cache that is confusing and which I have removed. As for URLHandler retrieval, level 2 query cache is the primary caching mechanism here.
