### ISSUE TITLE
URLHandler cache is not threadsafe

### ISSUE THREAD

**Issue by phillipuniverse** [BroadleafCommerce/BroadleafCommerce#1350]
This one should be backported.

We are doing this in the `URLHandlerService`:

```java
Pattern p = urlPatternMap.get(incomingUrl);
if (p == null) {
    p = Pattern.compile(incomingUrl);
    urlPatternMap.put(incomingUrl, p);
}
```

`urlPatternMap` is instantiated like so:

```java
protected LRUMap<String, Pattern> urlPatternMap = new LRUMap<String, Pattern>(10, 2000);
```

An `LRUMap` is explicitly not thread-safe as notated by their own Javadocs and could throw `NullPointerExceptions` when using it with concurrent threads.

Somewhat related to #1348.

**Comment by phillipuniverse** [comment]
Furthermore, the construction of this `LRUMap` is ludicrous:

```java
new LRUMap<String, Pattern>(10, 2000);
```

The 2nd parameter is a `loadFactor`. From the [HashMap javadocs](http://docs.oracle.com/javase/6/docs/api/java/util/HashMap.html):

> As a general rule, the default load factor (.75) offers a good tradeoff between time and space costs.

The `loadFactor` parameter is ratio for how full the map is allowed to get before it resizes to hold the additional capacity. This configuration essentially says "start with a capacity of 10 and then increase the size of the map at 20,000% capacity". Thus, this cache will only store, at most, 10 elements.

Actually, the first parameter of `10` is the maxSize. Original committer problably thought this read "give me an LRU map with an initial size of 10 and a max size of 2000. This should change to that intention, which would just be `new LRUMap<String, Pattern>(2000)`

**Comment by spprakash** [comment]
@phillipuniverse, the LRUMap in URLHandlerServiceImpl is of instance org.codehaus.jackson.map.util.LRUMap - which creates the map with initial entries 10 and max entries as 2000. So I believe the initialization is correct only.

**Comment by phillipuniverse** [comment]
@spprakash ah, excellent catch. Sounds like this would then just affect 4.0+. Looks like I changed all the LRUMaps from `org.codehaus.jackson` to use Apache commons instead when I did the Jackson upgrade, inadvertently changing the semantics of this constructor.
