### ISSUE TITLE
Fix performance and usage issues associated with LRUMaps

### ISSUE THREAD

**Issue by bpolster** [BroadleafCommerce/BroadleafCommerce#1357]
Prior fixes for #1350 introduced synchronized collections everywhere LRUMaps were used.

This could cause performance issues and also uncovered a potential issue where a race condition exists in our LRUMap usage.  For example, a contains followed by a "get" where theoretically we could get a null on the "get".

**Comment by jefffischer** [comment]
These changes look ok to me and don't cause problems under load. Marking this as fixed and closing.
