### ISSUE TITLE
Compilation error due to double quotes in org.broadleafcommerce.common.logging.SupportLogger.java

### ISSUE THREAD

**Issue by sivaprasadreddy** [BroadleafCommerce/BroadleafCommerce#1363]
While building BroadleafCommerce I am getting compilation error because of double quotes in org.broadleafcommerce.common.logging.SupportLogger.java at line 49 (e.g. “Enterprise Module — …”).

Note the MS word style quotes (e.g. “Enterprise Module — …”)

**Comment by bpolster** [comment]
This issue hasn't been impacting our builds but I went ahead and replaced the quotes in latest develop branch.
