### ISSUE TITLE
Friendly permissions not supported for sections with ceiling entity null

### ISSUE THREAD

**Issue by lakshmikalyani** [BroadleafCommerce/BroadleafCommerce#1365]
If friendly permission is mapped to a section with ceiling entity null a 403 access forbidden error is thrown in cms.

**Comment by phillipuniverse** [comment]
Can you give a bit more information? As in, the SQL that you're talking about?

Also I assume this is on 3.1.13-GA, can you confirm?

**Comment by bpolster** [comment]
@phillipuniverse I think this is when you add a custom admin section that doesn't reference an entity but then you want to add a permission for it as well.    This is technically an enhancement as we haven't built support for this yet - but it makes sense to do so especially if it is simple.

**Comment by lakshmikalyani** [comment]
@phillipuniverse : Yes this issue is on 3.1.13-GA. I have a custom section that doesn't have a ceiling entity and the permission is defined using the spring security annotation @Secured at class level.As per the new Role structure in 3.1.13-GA I have created friendly permissions and mapped it to the section and role. And also the friendly to child permission mapping in the permission xref(blc_admin_permission_xref) table.This is throwing a 403 error when that section is accessed from cms.
If the child permission is also mapped to the role this seems to be working. Let me know if there is any other solution that can be implemented for this so that this will also be in sync with sections with ceiling entities mapped.

Thanks for your help in advance.
