### ISSUE TITLE
Timed metadata caching does not extend between different persistence requests

### ISSUE THREAD

**Issue by phillipuniverse** [BroadleafCommerce/BroadleafCommerce#1369]
If you set the `cache.entity.dao.metadata.ttl` to anything other than `0` (don't cache) or `-1` (cache indefinitely) it doesn't actually do what you intend. So if you set it up like this (cache for 2 seconds):

``` config
cache.entity.dao.metadata.ttl=2000
```

The cache does not actually persist between persistence requests. For instance, if I invoke `service.getClassMetadata()` 2x in a row for the same entity (or for different entities that share a relationship to an entity) metadata gets built multiple times.

The reason for this is because `DynamicEntityDaoImpl` (the component that holds the cach) is declared as `@Scope("prototype")`, along with other components of the admin persistence pipeline. On every single request through the admin pipeline, a new instance of `PersistenceManager` is created (see `PersistenceManagerFactory`; it looks up the `PersistenceManager` bean which is also declared as `prototype` scope) which in turn creates a new instance of `DynamicEntityDao`. Since we have a brand new instance, I think something goes wrong with the cache timing and thus the metadata cache is flushed too early.

It's also possible that just this number specifically is too low. This borks bad when you go to view Orders in the admin because computing the metadata for `OrderItem` is very expensive (it contains Product, Sku and Category). It is possible that computation along takes > 2 seconds, but the prototype nature of these beans and the fact that they are re-instantiated on every admin persistence pipeline request was confusing.

**Comment by deepubansal** [comment]
I was just checking through how does the entity caching works and noticed below code.

Shouldn't the statement on line no. 213 in `DynamicEntityDaoImpl` be `return false;` ?

```
   @Override
    public boolean useCache() {
        if (cacheEntityMetaDataTtl < 0) {
            return true;
        }
        if (cacheEntityMetaDataTtl == 0) {
            return false;
        } else {
            if ((System.currentTimeMillis() - lastCacheFlushTime) > cacheEntityMetaDataTtl) {
                lastCacheFlushTime = System.currentTimeMillis();
                METADATA_CACHE.clear();
                DynamicDaoHelperImpl.POLYMORPHIC_ENTITY_CACHE.clear();
                DynamicDaoHelperImpl.POLYMORPHIC_ENTITY_CACHE_WO_EXCLUSIONS.clear();
                return true; // cache is empty.. Shouldn't this be return false ?
            } else {
                return true;
            }
        }
    }

```

**Comment by bpolster** [comment]
@deepubansal Thanks for the comment.   Assigning to @jefffischer for further review.
