### ISSUE TITLE
DynamicEntityDao is difficult to inject into other places

### ISSUE THREAD

**Issue by phillipuniverse** [BroadleafCommerce/BroadleafCommerce#1370]
If you try to do inject `DynamicEntityDao` and do anything meaningful with it (like build metadata for an entity or get all polymorphic instances of an entity) you can't without doing this since it is a prototype bean:

``` java
public class MyComponent {
    @Resource
    protected DynamicEntityDao ddao;

    @PersistenceContext(unitName = "blPU")
    protected EntityManager em;

    @PostConstruct
    public void init() {
        dynamicEntityDao.setStandardEntityManager(em);
    }
```

I suspect that this is because when the `PersistenceManager` creates a new instance of `DynamicEntityDao` (whose bean scope is `prototype`) it is also responsible for setting the entity manager that the DDAO uses. The `standardEntityManager` property is currently un-annotated.

It seems like we should still annotate this property in DDAO for other components to utilize it easily since whatever `PersistenceManager` does will reset it anyway. @jefffischer do you see a problem with that? Seems like a very straightforward enhancement.

**Comment by jefffischer** [comment]
Use an instance of DynamicDaoHelperImpl instead.
