### ISSUE TITLE
When changing the users email in DemoSite, it logs the user out

### ISSUE THREAD

**Issue by ncrum** [BroadleafCommerce/BroadleafCommerce#1383]
Referencing BroadleafCommerce/QA#616

**Comment by jefffischer** [comment]
@ncrum I'm going to revert this commit - It should have been part of a pull request against core.

**Comment by ncrum** [comment]
Changing made here are describing in QA, but to recap: I modified the update account form to require a password verification to change the email (or first/last name). This allows us to properly re-authenticate the user if the username is changed and Spring logs them out.
