### ISSUE TITLE
Deleting an image asset from admin ui does not remove the asset from disk

### ISSUE THREAD

**Issue by johnsebastian** [BroadleafCommerce/BroadleafCommerce#1385]
While deleting a media asset, no method invocation was made to BroadleafFileServiceImpl.removeResource(String resourceName). To fix this I have added a new StaticAssetPersistenceEventHandler which extends PersistenceManagerEventHandlerAdapter, and in postRemove(), added the function call to removeResource(String resourceName) in order to remove the asset from Disk.

**Comment by johnsebastian** [comment]
This is closed

**Comment by jefffischer** [comment]
This is a duplicate of https://github.com/BroadleafCommerce/BroadleafCommerce/issues/1431

**Comment by BalanJayavictor** [comment]
Can this fix be used for older versions of Broadleaf?
