### ISSUE TITLE
Product sandbox Change Details displaying un-modified fields in admin

### ISSUE THREAD

**Issue by ncrum** [BroadleafCommerce/BroadleafCommerce#1427]
Details:
+ Make a change to a product, such as sales price
+ Go to My Changes and promote it
+ View Details for the Promoted Item

Problems:
+ overrideGeneratedUrl showing as being changed from null to blank, it should not show at all.
+ ID showing as being changed from blank to an integer, it should not at all since it is a primary key
+ parent category is showing up as changing from blank to the current value after promotion, it is not being changed at all, so it should not show up either.

Fixed this by changing BasicFieldPersistenceProvider to treat null as false.

**Comment by phillipuniverse** [comment]
Moving this out of the 4.1 milestone and closing. This is not actually an issue, the reason
