### ISSUE TITLE
500 Error in Admin when entity not found

### ISSUE THREAD

**Issue by jfleschler** [BroadleafCommerce/BroadleafCommerce#1454]
In the case of an entity not found error, we want to throw a new specific exception ("EntityNotFoundException") that can be targeted in our exception handler.

Once we have the correct exception identified we can redirect the user to an appropriate page, instead of throwing a stack trace.

**Comment by danielcolgrove** [comment]
@regcole tested this and found that instead of a 500 error, the user now gets a 403 error.  Reopening and assigning to 4.0.2.

**Comment by phillipuniverse** [comment]
@danielcolgrove this should not be re-opened as this issue is now apart of a release. Something new needs to be opened instead, while this remains preserved.

**Comment by danielcolgrove** [comment]
Closing this issue.  Will open a new issue for the 403 error that is now seen.
