### ISSUE TITLE
4.0.0-RC1 app -Exception while Deploy to Jboss

### ISSUE THREAD

**Issue by sumit784** [BroadleafCommerce/BroadleafCommerce#1503]
Hi, 
I am succesfully running a BLC application on 3.1. version for 6 months now.  Today I have updated to 4.0.0-RC1, updated the pom files, xml configs and other java classes. 
So,all the 3 application core, site, admin and building properly after the udpate. But while deploying, I am getting the following exception :- 

<b>
JBWEB000287: Exception sending context initialized event to listener instance of class org.broadleafcommerce.common.web.extensibility.MergeContextLoader: org.springframework.beans.factory.BeanCreationException: 
Error creating bean with name 'applicationEventMulticaster': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private java.util.concurrent.Executor org.broadleafcommerce.common.event.BroadleafApplicationEventMulticaster.taskExecutor; nested exception is org.springframework.beans.factory.BeanDefinitionStoreException: 
Invalid bean definition with name 'blJsResources' defined in resource loaded from byte array: Could not resolve parent bean definition 'siteJsResourceRequestHandlerBase'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: 
No bean named 'siteJsResourceRequestHandlerBase' is defined
</b>
So, I checked for this config, and I could only see the parent ref in "site/applicationContext.xml" ( <bean id="blJsResources" parent="siteJsResourceRequestHandlerBase" />). 

So, Am I missing something here ? Kindly help. I am stuck . 

FYI :-
1) I am using Jboss througout and there are no issue with server. 
2) I have not yet changed / updated anything in my existing DB. 

Kindly help ASAP. Thanks in advance. 

- Sumit Rathore

**Comment by danielcolgrove** [comment]
Hi Sumit,  please direct this support issue to the forums for the community to respond.
