### ISSUE TITLE
Unit Test Failure in SystemTimeTest.testAsCalendarBoolean

### ISSUE THREAD

**Issue by alfanse** [BroadleafCommerce/BroadleafCommerce#1529]
newbie to broadleaf here.
I have command line build failure with a single unit test failing - repeatably - in common libraries.
I did git pull on: remote.origin.url=https://github.com/BroadleafCommerce/BroadleafCommerce.git
then mvn clean verify
...
Running org.broadleafcommerce.common.time.SystemTimeTest
Tests run: 12, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.02 sec <<< FAILURE!

Results :

Failed tests: testAsCalendarBoolean(org.broadleafcommerce.common.time.SystemTimeTest): expected:<java.util.GregorianCalendar[time=?,areFieldsSet=false,areAllFieldsSet=false,lenient=true,zone=sun.util.calendar.ZoneInfo[id="Europe/London",offset=0,dstSavings=3600000,useDaylight=true,transitions=242,lastRule=java.util.SimpleTimeZone[id=Europe/London,offset=0,dstSavings=3600000,useDaylight=true,startYear=0,startMode=2,startMonth=2,startDay=-1,startDayOfWeek=1,startTime=3600000,startTimeMode=2,endMode=2,endMonth=9,endDay=-1,endDayOfWeek=1,endTime=3600000,endTimeMode=2]],firstDayOfWeek=2,minimalDaysInFirstWeek=4,ERA=?,YEAR=2010,MONTH=1,WEEK_OF_YEAR=?,WEEK_OF_MONTH=?,DAY_OF_MONTH=2,DAY_OF_YEAR=?,DAY_OF_WEEK=?,DAY_OF_WEEK_IN_MONTH=?,AM_PM=0,HOUR=0,HOUR_OF_DAY=0,MINUTE=0,SECOND=0,MILLISECOND=0,ZONE_OFFSET=?,DST_OFFSET=?]> but was:<java.util.GregorianCalendar[time=?,areFieldsSet=false,areAllFieldsSet=true,lenient=true,zone=sun.util.calendar.ZoneInfo[id="Europe/London",offset=0,dstSavings=3600000,useDaylight=true,transitions=242,lastRule=java.util.SimpleTimeZone[id=Europe/London,offset=0,dstSavings=3600000,useDaylight=true,startYear=0,startMode=2,startMonth=2,startDay=-1,startDayOfWeek=1,startTime=3600000,startTimeMode=2,endMode=2,endMonth=9,endDay=-1,endDayOfWeek=1,endTime=3600000,endTimeMode=2]],firstDayOfWeek=1,minimalDaysInFirstWeek=1,ERA=1,YEAR=2010,MONTH=1,WEEK_OF_YEAR=6,WEEK_OF_MONTH=1,DAY_OF_MONTH=2,DAY_OF_YEAR=33,DAY_OF_WEEK=3,DAY_OF_WEEK_IN_MONTH=1,AM_PM=0,HOUR=3,HOUR_OF_DAY=0,MINUTE=0,SECOND=0,MILLISECOND=0,ZONE_OFFSET=0,DST_OFFSET=0]>

Tests run: 35, Failures: 1, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] BroadleafCommerce .................................. SUCCESS [ 2.027 s]
[INFO] BroadleafCommerce Common Libraries ................. FAILURE [ 10.155 s]

My system:
mvn --version
Apache Maven 3.3.3 (7994120775791599e205a5524ec3e0dfe41d4a06; 2015-04-22T12:57:37+01:00)
Maven home: /usr/local/Cellar/maven/3.3.3/libexec
Java version: 1.8.0_45, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.10.4", arch: "x86_64", family: "mac"

Any help gratefully received,
Regards
A

**Comment by bpolster** [comment]
Which version of Broadleaf are you building against?

**Comment by phillipuniverse** [comment]
Can you also rebuild with a `-X` or `-e`? Maven will give more detailed output with those flags.

**Comment by alfanse** [comment]
Hi Bpolster, I have now run against:
git checkout  origin/4.0.0_Performance -t
git checkout origin/BroadleafCommerce-4.1.x -t
Both are failing with the same error.

I fired up intellij and it repeatably fails at the same point.
Seems the class SystemTime does something the unit test disagrees with.
I've don't understand the requirement deeply enough to figure out which is wrong, the test of the method.

Are you able to recreate the problem?

Running org.broadleafcommerce.common.time.SystemTimeTest
Tests run: 12, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.024 sec <<< FAILURE!

Results :

Failed tests:   testAsCalendarBoolean(org.broadleafcommerce.common.time.SystemTimeTest): expected:<java.util.GregorianCalendar[time=?,areFieldsSet=false,areAllFieldsSet=false,lenient=true,zone=sun.util.calendar.ZoneInfo[id="Europe/London",offset=0,dstSavings=3600000,useDaylight=true,transitions=242,lastRule=java.util.SimpleTimeZone[id=Europe/London,offset=0,dstSavings=3600000,useDaylight=true,startYear=0,startMode=2,startMonth=2,startDay=-1,startDayOfWeek=1,startTime=3600000,startTimeMode=2,endMode=2,endMonth=9,endDay=-1,endDayOfWeek=1,endTime=3600000,endTimeMode=2]],firstDayOfWeek=2,minimalDaysInFirstWeek=4,ERA=?,YEAR=2010,MONTH=1,WEEK_OF_YEAR=?,WEEK_OF_MONTH=?,DAY_OF_MONTH=2,DAY_OF_YEAR=?,DAY_OF_WEEK=?,DAY_OF_WEEK_IN_MONTH=?,AM_PM=0,HOUR=0,HOUR_OF_DAY=0,MINUTE=0,SECOND=0,MILLISECOND=0,ZONE_OFFSET=?,DST_OFFSET=?]> but was:<java.util.GregorianCalendar[time=?,areFieldsSet=false,areAllFieldsSet=true,lenient=true,zone=sun.util.calendar.ZoneInfo[id="Europe/London",offset=0,dstSavings=3600000,useDaylight=true,transitions=242,lastRule=java.util.SimpleTimeZone[id=Europe/London,offset=0,dstSavings=3600000,useDaylight=true,startYear=0,startMode=2,startMonth=2,startDay=-1,startDayOfWeek=1,startTime=3600000,startTimeMode=2,endMode=2,endMonth=9,endDay=-1,endDayOfWeek=1,endTime=3600000,endTimeMode=2]],firstDayOfWeek=1,minimalDaysInFirstWeek=1,ERA=1,YEAR=2010,MONTH=1,WEEK_OF_YEAR=6,WEEK_OF_MONTH=1,DAY_OF_MONTH=2,DAY_OF_YEAR=33,DAY_OF_WEEK=3,DAY_OF_WEEK_IN_MONTH=1,AM_PM=0,HOUR=3,HOUR_OF_DAY=0,MINUTE=0,SECOND=0,MILLISECOND=0,ZONE_OFFSET=0,DST_OFFSET=0]>

Tests run: 35, Failures: 1, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] BroadleafCommerce .................................. SUCCESS [  1.591 s]
[INFO] BroadleafCommerce Common Libraries ................. FAILURE [  9.036 s]

I posted a related Issue suggesting you make the build public, but that got closed, not easy to know if its a problem isolated to my environment. :(
bit sad about that: https://github.com/BroadleafCommerce/BroadleafCommerce/issues/1530

**Comment by alfanse** [comment]
Further to the above, I forked and hooked up to circleci
https://circleci.com/gh/alfanse/BroadleafCommerce/4
only to find the app built.
Conclusion, the failure is something to do with java on a mac :(

Best to close this and move on...

**Comment by phillipuniverse** [comment]
Well, all of us regularly build with a Mac:

```console
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=512m; support was removed in 8.0
Apache Maven 3.3.3 (7994120775791599e205a5524ec3e0dfe41d4a06; 2015-04-22T06:57:37-05:00)
Maven home: /usr/local/Cellar/maven/3.3.3/libexec
Java version: 1.8.0_51, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_51.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.10.4", arch: "x86_64", family: "mac"
```

I was going to suggest it had to do with the locale that the JVM detects but judging from your output it looks like that's `en_US`.

What happens when you build with a `-X` and/or `-e`? e.g. `mvn -X clean install`.

And you said it fails at the same point in IntelliJ, which point is that? There are multiple asserts in that test method, which one fails and why?

**Comment by alfanse** [comment]
Oh, that has suprised me,
Both assert fail.
I commented out one to see if the other would work.
Do you want the assertion output?

Not sure what you want from the mvn -X command, its rather verbose…
I’ll attach as email if thats prefered?

**Comment by alfanse** [comment]
Hi So I noticed you use a more recent version of java, so I updated the mac
to:

mvn -version

Apache Maven 3.3.3 (7994120775791599e205a5524ec3e0dfe41d4a06;
2015-04-22T12:57:37+01:00)

Maven home: /usr/local/Cellar/maven/3.3.3/libexec

Java version: 1.8.0_51, vendor: Oracle Corporation

Java home:
/Library/Java/JavaVirtualMachines/jdk1.8.0_51.jdk/Contents/Home/jre

Default locale: en_US, platform encoding: UTF-8

OS name: "mac os x", version: "10.10.4", arch: "x86_64", family: "mac"

build fails, same reason, so I ran in isolation with intellij:
SystemTimeTest in intellij with the first assert off:

  public void testAsCalendarBoolean() {
        Calendar cal = new GregorianCalendar(2010, 1, 2, 3, 4, 5);
        cal.set(Calendar.MILLISECOND, 3); // Add a few milliseconds
for good measure
        expect(mockTimeSource.timeInMillis()).andReturn(cal.getTimeInMillis()).atLeastOnce();
        replay(mockTimeSource);
        SystemTime.setGlobalTimeSource(mockTimeSource);
        Calendar calMidnight = new GregorianCalendar(2010, 1, 2, 0, 0, 0);
        calMidnight.set(Calendar.MILLISECOND, 0);
//        assertEquals(calMidnight, SystemTime.asCalendar(false));
        assertEquals(cal, SystemTime.asCalendar(true));
        verify();
    }


junit.framework.AssertionFailedError:
Expected
:java.util.GregorianCalendar[time=1265079845003,areFieldsSet=true,areAllFieldsSet=false,lenient=true,zone=sun.util.calendar.ZoneInfo[id="Europe/London",offset=0,dstSavings=3600000,useDaylight=true,transitions=242,lastRule=java.util.SimpleTimeZone[id=Europe/London,offset=0,dstSavings=3600000,useDaylight=true,startYear=0,startMode=2,startMonth=2,startDay=-1,startDayOfWeek=1,startTime=3600000,startTimeMode=2,endMode=2,endMonth=9,endDay=-1,endDayOfWeek=1,endTime=3600000,endTimeMode=2]],firstDayOfWeek=2,minimalDaysInFirstWeek=4,ERA=?,YEAR=2010,MONTH=1,WEEK_OF_YEAR=?,WEEK_OF_MONTH=?,DAY_OF_MONTH=2,DAY_OF_YEAR=?,DAY_OF_WEEK=?,DAY_OF_WEEK_IN_MONTH=?,AM_PM=0,HOUR=3,HOUR_OF_DAY=3,MINUTE=4,SECOND=5,MILLISECOND=3,ZONE_OFFSET=?,DST_OFFSET=?]
Actual
:java.util.GregorianCalendar[time=1265079845003,areFieldsSet=true,areAllFieldsSet=true,lenient=true,zone=sun.util.calendar.ZoneInfo[id="Europe/London",offset=0,dstSavings=3600000,useDaylight=true,transitions=242,lastRule=java.util.SimpleTimeZone[id=Europe/London,offset=0,dstSavings=3600000,useDaylight=true,startYear=0,startMode=2,startMonth=2,startDay=-1,startDayOfWeek=1,startTime=3600000,startTimeMode=2,endMode=2,endMonth=9,endDay=-1,endDayOfWeek=1,endTime=3600000,endTimeMode=2]],firstDayOfWeek=1,minimalDaysInFirstWeek=1,ERA=1,YEAR=2010,MONTH=1,WEEK_OF_YEAR=6,WEEK_OF_MONTH=1,DAY_OF_MONTH=2,DAY_OF_YEAR=33,DAY_OF_WEEK=3,DAY_OF_WEEK_IN_MONTH=1,AM_PM=0,HOUR=3,HOUR_OF_DAY=3,MINUTE=4,SECOND=5,MILLISECOND=3,ZONE_OFFSET=0,DST_OFFSET=0]

And with first asset on:

public void testAsCalendarBoolean() {
    Calendar cal = new GregorianCalendar(2010, 1, 2, 3, 4, 5);
    cal.set(Calendar.MILLISECOND, 3); // Add a few milliseconds for good measure
    expect(mockTimeSource.timeInMillis()).andReturn(cal.getTimeInMillis()).atLeastOnce();
    replay(mockTimeSource);
    SystemTime.setGlobalTimeSource(mockTimeSource);
    Calendar calMidnight = new GregorianCalendar(2010, 1, 2, 0, 0, 0);
    calMidnight.set(Calendar.MILLISECOND, 0);
    assertEquals(calMidnight, SystemTime.asCalendar(false));
    assertEquals(cal, SystemTime.asCalendar(true));
    verify();
}


we get the result:

junit.framework.AssertionFailedError:
Expected
:java.util.GregorianCalendar[time=?,areFieldsSet=false,areAllFieldsSet=false,lenient=true,zone=sun.util.calendar.ZoneInfo[id="Europe/London",offset=0,dstSavings=3600000,useDaylight=true,transitions=242,lastRule=java.util.SimpleTimeZone[id=Europe/London,offset=0,dstSavings=3600000,useDaylight=true,startYear=0,startMode=2,startMonth=2,startDay=-1,startDayOfWeek=1,startTime=3600000,startTimeMode=2,endMode=2,endMonth=9,endDay=-1,endDayOfWeek=1,endTime=3600000,endTimeMode=2]],firstDayOfWeek=2,minimalDaysInFirstWeek=4,ERA=?,YEAR=2010,MONTH=1,WEEK_OF_YEAR=?,WEEK_OF_MONTH=?,DAY_OF_MONTH=2,DAY_OF_YEAR=?,DAY_OF_WEEK=?,DAY_OF_WEEK_IN_MONTH=?,AM_PM=0,HOUR=0,HOUR_OF_DAY=0,MINUTE=0,SECOND=0,MILLISECOND=0,ZONE_OFFSET=?,DST_OFFSET=?]
Actual
:java.util.GregorianCalendar[time=?,areFieldsSet=false,areAllFieldsSet=true,lenient=true,zone=sun.util.calendar.ZoneInfo[id="Europe/London",offset=0,dstSavings=3600000,useDaylight=true,transitions=242,lastRule=java.util.SimpleTimeZone[id=Europe/London,offset=0,dstSavings=3600000,useDaylight=true,startYear=0,startMode=2,startMonth=2,startDay=-1,startDayOfWeek=1,startTime=3600000,startTimeMode=2,endMode=2,endMonth=9,endDay=-1,endDayOfWeek=1,endTime=3600000,endTimeMode=2]],firstDayOfWeek=1,minimalDaysInFirstWeek=1,ERA=1,YEAR=2010,MONTH=1,WEEK_OF_YEAR=6,WEEK_OF_MONTH=1,DAY_OF_MONTH=2,DAY_OF_YEAR=33,DAY_OF_WEEK=3,DAY_OF_WEEK_IN_MONTH=1,AM_PM=0,HOUR=3,HOUR_OF_DAY=0,MINUTE=0,SECOND=0,MILLISECOND=0,ZONE_OFFSET=0,DST_OFFSET=0]


Thanks for taking the time to investigate,
sorry this isn’t easier!

Regards
Alex

**Comment by alfanse** [comment]
Right its a region settings bug.
When I switched my mac to use Regions: United States
the unit test passed.
<img width="371" alt="screen shot 2015-07-29 at 7 31 46 am" src="https://cloud.githubusercontent.com/assets/8712893/8951276/ed0ca170-35c3-11e5-8743-15d9fc590108.png">

When I have Region set to United Kingdom the unit test fails:
<img width="369" alt="screen shot 2015-07-29 at 07 33 13" src="https://cloud.githubusercontent.com/assets/8712893/8951290/28456cc2-35c4-11e5-892b-7ad58906d09d.png">

**Comment by bpolster** [comment]
Thanks for the clarification and debugging on this issue.    Flagging as a bug to investigate further.
