### ISSUE TITLE
how to add skuattribues to blc_field for search?

### ISSUE THREAD

**Issue by wenmangbo** [BroadleafCommerce/BroadleafCommerce#1534]
<img width="806" alt="screen shot 2015-08-11 at 20 20 47" src="https://cloud.githubusercontent.com/assets/13674429/9199638/1fd6b57a-4076-11e5-9c63-4e2694f5e223.png">
I want to add sku attribue catalog.  How to filled blc_field?
Abbreviation:catalog
Facet_field_type:ss
Property_name: allSkus.skuAttributes(catalog).value  !no sure about it.
searchable:1
Kind Regards

**Comment by wenmangbo** [comment]
<img width="806" alt="screen shot 2015-08-11 at 20 20 47" src="https://cloud.githubusercontent.com/assets/13674429/9199632/14f61164-4076-11e5-88e8-06e6a519c909.png">

**Comment by bpolster** [comment]
These questions should be sent to the Broadleaf forums
