### ISSUE TITLE
Unable to find 4.0.3-GA tagged code in GitHub

### ISSUE THREAD

**Issue by spprakash** [BroadleafCommerce/BroadleafCommerce#1535]
Hi,

Looking at the release notes, there were couple of release in the last one month and the latest version is 4.0.3-GA. But I couldn't find any such branch/tag in github. Can you please provide the details from where I can get the 4.0.3-GA code base.

-Surya.

**Comment by bpolster** [comment]
Community releases will now trail our professional releases by up to 12 months.
