### ISSUE TITLE
In some instances the invalidation of the Order Payment isn't persisted

### ISSUE THREAD

**Issue by elbertbautista** [BroadleafCommerce/BroadleafCommerce#1538]
looking at the `markPaymentAsInvalid` method in `org.broadleafcommerce.core.payment.service.DefaultPaymentGatewayCheckoutService` - the intention is to set the payments and all of its child transactions to `Archived` as specified in this issue: https://github.com/BroadleafCommerce/BroadleafCommerce/issues/1160 --- 

However, there does not seem to be a wrapping transaction, so not sure how this change is actually persisted. An example scenario may be when you get an unsuccessful response back from the gateway.

This change seems to be in 3.1.9-GA+

```
    @Override
    public void markPaymentAsInvalid(Long orderPaymentId) {
        OrderPayment payment = orderPaymentService.readPaymentById(orderPaymentId);
        if (payment == null) {
            throw new IllegalArgumentException("Could not find payment with id " + orderPaymentId);
        }
        // Do not do an actual delete here, otherwise Hibernate will screw up the relationships by setting parent transactions
        // to null because of the cascades. This manifests itself when you have an AUTHORIZE_AND_CAPTURE transaction and
        // then an immediate VOID (like if there is an exception in the checkout workflow). The VOID transaction should
        // have its parent set to the AUTHORIZE_AND_CAPTURE transaction which works up until we call Hibernate's delete
        // on the payment. By cascading down to the transaction, Hibernate goes and removes the parentTransaction relationship
        // from the VOID transaction
        // The fix is to set archived statuses manually and not rely on Hibernate's @SqlDelete
        payment.setArchived('Y');
        for (PaymentTransaction transaction : payment.getTransactions()) {
            transaction.setArchived('Y');
        }
    }
```

One solution is to explicitly save the payment after setting the flag. Like so:
```
        payment.setArchived('Y');
        for (PaymentTransaction transaction : payment.getTransactions()) {
            transaction.setArchived('Y');
        }
        orderPaymentService.save(payment);
```

This should be tested and verified against the following scenarios:

**Test 1**: Submit a successful AUTH_CAPTURE transaction (i.e. valid CC# etc...)
**Expected DB Result 1**: 2 Order Payments (1 TEMP archived, 1 "gateway" un-archived), The unarchived gateway payment should have un-archived transaction with a status of "successful"

**Test 2**: Submit an unsuccessful AUTH_CAPTURE transaction (i.e. invalid CC# etc...)
**Expected DB Result 2**: 2 Order Payments (1 TEMP archived, 1 "gateway" archived). The archived gateway payment should have an archived transaction with a status of "unsuccessful"

**Test 3**: Submit a successful AUTH_CAPTURE transaction (i.e. valid CC# etc...) however throw an exception somewhere else down the line (e.g. in `PaymentGatewayAbstractController` line 186 - the checkout workflow is invoked, so throw an exception in `CompleteOrderActivity` to simulate something going wrong so as to invoke all the roll back handlers)
**Expected DB Result 3**: 2 Order Payments (1 TEMP archived, 1 "gateway" archived). The archived gateway payment should have 2 archived transactions: 1 AUTH_CAPTURE archived transaction with a status of "successful" and 1 VOID archived transaction with a status of "successful"

**Comment by AustinMRooke** [comment]
Having tested this with the current 4.0.4 Snapshot build, each test result matched the expected DB result. This has been verified that it works as expected.

**Comment by elbertbautista** [comment]
Just some updates as to why the above is working: 

`OrderPayment payment = orderPaymentService.readPaymentById(orderPaymentId);` means that the current entity is managed by the EntityManager and the updates to this instance are being flushed and persisted to the DB by what looks like the finally block of the CartStateFilter, specifically this:

```
            if (lockObject != null) {
                orderLockManager.releaseLock(lockObject);
            }
``` 

@AustinMRooke is looking into exactly what is causing the flush and why some implementations aren't behaving this way and flushing consistently.

**Comment by elbertbautista** [comment]
To wrap up the discussion here, the reason this works on 4.0.x line is because of the introduction of the `org.broadleafcommerce.core.web.order.DatabaseOrderLockManager` which was introduced as the default lock manager in the 4.0 line. When the managed OrderPayment entity was changed, the finally block of the `CartStateFilter` invokes the `DatabaseOrderLockManager` which invokes a transaction utility that proceeds to clean up any dirty state and flushes all changes to the DB. 

Since the DatabaseOrderLockManager was not introduced until the 4.0 line, this issue affects versions:
- 3.1.9-GA
- 3.1.10-GA
- 3.1.11-GA
- 3.1.12-GA
- 3.1.13-GA

and **ALL** implementations that use the `org.broadleafcommerce.core.web.order.SessionOrderLockManager`

The fix introduced here explicitly calls save on the managed instance and should in all cases persist the changes.
