### ISSUE TITLE
Not able to remove product if the product is added to order

### ISSUE THREAD

**Issue by noopuraspire** [BroadleafCommerce/BroadleafCommerce#1543]
When I try to remove product, it gives me above error

HTTP Status 500 - org.springframework.web.util.NestedServletException: Request processing failed; nested exception is org.springframework.dao.DataIntegrityViolationException: Cannot delete or update a parent row: a foreign key constraint fails (`broadleaf`.`BLC_DISCRETE_ORDER_ITEM`, CONSTRAINT `FKBC3A8A84B78C9977` FOREIGN KEY (`SKU_ID`) REFERENCES `BLC_SKU` (`SKU_ID`)); SQL [n/a]; constraint [null]; nested exception is org.hibernate.exception.ConstraintViolationException: Cannot delete or update a parent row: a foreign key constraint fails (`broadleaf`.`BLC_DISCRETE_ORDER_ITEM`, CONSTRAINT `FKBC3A8A84B78C9977` FOREIGN KEY (`SKU_ID`) REFERENCES `BLC_SKU` (`SKU_ID`))

**Comment by RapidTransit** [comment]
What version are you using? 
Does your ProductImpl contain:
`@SQLDelete(sql = "UPDATE BLC_PRODUCT SET ARCHIVED = 'Y' WHERE PRODUCT_ID = ?")`

When a product is deleted it should just set it as archived
