### ISSUE TITLE
No  information is provided when Password Change successfully for Site 

### ISSUE THREAD

**Issue by saifulazad** [BroadleafCommerce/BroadleafCommerce#1544]
When an user remove an address it show message "Removed address" . It is also applicable for Add new address. But there are no information about  Password Change successfully at BroadleafChangePasswordController class when user successfully change password

**Comment by suhaimsyed** [comment]
I assume the below highlighted code should solve the problem BroadleafChangePasswordController

public String processChangePassword(HttpServletRequest request, Model model, ChangePasswordForm form, BindingResult result, RedirectAttributes redirectAttributes) throws ServiceException {
        PasswordChange passwordChange = new PasswordChange(CustomerState.getCustomer().getUsername());
        passwordChange.setCurrentPassword(form.getCurrentPassword());
        passwordChange.setNewPassword(form.getNewPassword());
        passwordChange.setNewPasswordConfirm(form.getNewPasswordConfirm());
        changePasswordValidator.validate(passwordChange, result);
        if (result.hasErrors()) {
            return getChangePasswordView();
        }
        customerService.changePassword(passwordChange);
        **model.addAttribute("successMessage", getPasswordChangedMessage());
        return viewChangePassword(request, model);**
    }
