### ISSUE TITLE
Not able to sort in REST 

### ISSUE THREAD

**Issue by noopuraspire** [BroadleafCommerce/BroadleafCommerce#1545]
I'm using REST API, and I'm getting all products using api/v1/catalog/search/products?q=_. I know that filtering, searching and sorting is done using solr, so I'm using catalog/search/products?q=_&sort=name+asc for sorting products by product name. But I'm to getting JSON sorted by product name.

**Comment by AbdelRahmaneB** [comment]
So you are getting what you want (the product name) !! :)
