### ISSUE TITLE
Problem with adding additional skus for a product with product options

### ISSUE THREAD

**Issue by sibuyas** [BroadleafCommerce/BroadleafCommerce#1546]
**Broadleaf Framework** : 3.1.13-GA
**Admin demo project** : 3.1.13-GA

**Steps to reproduce**

1.) Go to demo admin
2.) Go to Catalog - Products and select a product
3.) Then from Product Options tab add a product option
4.) Go to Catalog - Product Options and select the product option you added in step 3.
5.) Then add a new allowed value to the selected product option
6.) Go back to the product selected in step 2.
7.) Then from the Product Options tab add an additional sku

**Expected results**: You can add a sku with the newly created product option value

**Actual results**: The newly created allowed value does not appear in the drop-down list for the product option.

This also happens in the current demo version.

**Comment by sibuyas** [comment]
The problem comes from caching the metadata properties in org.broadleafcommerce.admin.server.service.handler.SkuCustomPersistenceHandler#METADATA_CACHE. The cache does not invalidate in the time specified in the property file. After removing the caching the problem doesn't reproduce anymore. 
This also solved another bug: when you add a product option to a product that already has a product option the newly added product option doesn't appear in the pop-up window when you want to add or edit an additional sku.

**Comment by Pr0TuX** [comment]
:) good to know, I'm curious why that cache was needed. 'Premature optimization is the root of all evil'

**Comment by phillipuniverse** [comment]
Thanks for the report, this seems like a pretty straightforward fix.

**Comment by jefffischer** [comment]
After tracing this behavior at runtime, the root of the problem appears to be that the value for ```cache.entity.dao.metadata.ttl``` in admin/broadleaf-open-admin-platform/src/main/resources/config/bc/admin/common.properties is -1, but the value for the same property specified in core/src/main/resources/runtime-properties/development-shared.properties is 2000. One would expect the value from core/... to override, but that does not appear to be working. Furthermore, given what SkuCustomPersistenceHandler#inspect is trying to achieve, it doesn't seem like a long ttl would ever make sense. The default ttl should be shortened to 2000 and the override bug should be addressed.
