### ISSUE TITLE
Is this repository still active?

### ISSUE THREAD

**Issue by dmarcaida** [BroadleafCommerce/BroadleafCommerce#1558]
I'm just curious since it hasn't been following the releases since 4.0.1-GA.

**Comment by bpolster** [comment]
Thanks for your question.     For the past eight months, Broadleaf has contributed the majority of our changes to a private repository with the intent to provide releases to the community for some functionality on a delayed basis.   In the near future, we plan to release version 5.0 of the software which will include a more restricted community license that better protects our IP while also allowing us to share more code with the community.

We will provide a detailed write-up as this nears completion which should occur within the next 60 days.    Feel free to reach out to us via our contact us page on our website for more information.
