### ISSUE TITLE
Why Broadleaf Commerce framework 5.0 source code is not available to download?

### ISSUE THREAD

**Issue by xbitlabs** [BroadleafCommerce/BroadleafCommerce#1567]
Why Broadleaf Commerce framework 5.0 source code is not available to download?

**Comment by RapidTransit** [comment]
+1 On this... I had to make some changes to rip out Solr for ElasticSearch (Better Nesting Support) and needed some features from later versions of Hibernate and Spring

**Comment by Jerry77oz** [comment]
While the source code is not currently available for the 5.0.x line, we do distribute the source as source jars available with the binaries on our nexus. 

Most IDEs should be able to auto-download these source jars and allow the developer to peruse the code.
