### ISSUE TITLE
BLC @ github is on version 4.0.11 (9+ months old) while most recent version is 5.1.0

### ISSUE THREAD

**Issue by brdloush** [BroadleafCommerce/BroadleafCommerce#1575]
It took me a while to write this, as I didn't want to sound like a troll.

But after 9+ months, this is really simply a shame.

Have you guys seen a recent Release notes (http://www.broadleafcommerce.com/docs/core/current/release-notes/5.1.0-ga) versus your recent public pom.xml?  

https://s27.postimg.org/t6zvx9eoj/blc_shame.png

**Comment by bpolster** [comment]
@brdloush Thank you for your message.   

We no longer publish our current releases to GitHub in real time.    The Broadleaf license module changed from Apache2 to a "Fair Use License" as part of the 5.0 release.

This was communicated in the following blog released at the time of the decision.   Here is a link to that blog:  http://www.broadleafcommerce.com/blog/broadleaf-announces-new-community-license

The source code is included in the release downloads and we are maintaining the public GitHub access for a convenience to those using BLC prior to 5.0.

Broadleaf customers have access to both community and enterprise source code.
