### ISSUE TITLE
The question about how to make a Chinese localization

### ISSUE THREAD

**Issue by sunday2** [BroadleafCommerce/BroadleafCommerce#1576]
Hello,i am the beginner who is from China.I  want to know how to make a Chinese localization and prevent it from being garbled.Thanks a lot for giving me a hand.

**Comment by hugolam008** [comment]
@sunday2 你的能跑起来吗？什么版本？什么环境？

**Comment by sunday2** [comment]
现在可以跑起来了，用的eclipse版本是mars2,broadleaf版本是5.0.1




------------------ 原始邮件 ------------------
发件人: "hugolam008";<notifications@github.com>;
发送时间: 2017年2月24日(星期五) 上午10:03
收件人: "BroadleafCommerce/BroadleafCommerce"<BroadleafCommerce@noreply.github.com>; 
抄送: "熊熊烈火"<160109794@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [BroadleafCommerce/BroadleafCommerce] The question about how tomake a Chinese localization (#1576)




@sunday2 你的能跑起来吗？什么版本？什么环境？

**Comment by hugolam008** [comment]
大神 邮箱继续聊？624605893@qq.com

**Comment by oleksiimiroshnyk** [comment]
https://www.broadleafcommerce.com/docs/core/current/broadleaf-concepts/internationalization/locale-resolution
