### ISSUE TITLE
Filter Product Options by the SKU Option Value XREF

### ISSUE THREAD

**Issue by bigal41** [BroadleafCommerce/BroadleafCommerce#1577]
If I have a 2 products that have a product option Color. They both show all colors on their product pages even though I stated which colors are available to each sku in the blc_sku_option_value_xref.

**Comment by linuxidefix** [comment]
I think it is more a demo or communityStarter problem than a framework problem.
It comes from the productOptions.html logic. 
It browses all possible product options without checking if the resultant combination matches an existing sku. Anyway you could not add the sku to the cart if it is not available.
Maybe it is done in purpose and it is up to us to implement that filter in the page ?
