### ISSUE TITLE
assetGrid was not defined, may be 'assetGrid.js' is lost.

### ISSUE THREAD

**Issue by yuedefeng** [BroadleafCommerce/BroadleafCommerce#1578]
BLCAdmin.assetGrid.initialize($assetGrid);

I can not find the defined of BLCAdmin.assetGrid.
My framework version is 5.05GA

**Comment by oleks85** [comment]
Are there any update on that issue? As I can see it still there in version 5.0.8-GA, 5.1* and 5.2*. 
Any thoughts when it be fixed?

**Comment by Yinzhe-Qi** [comment]
Same issue encountered, anybody got a solution???

**Comment by Yinzhe-Qi** [comment]
Simply commenting out all occurrences of `BLCAdmin.assetGrid.initialize` in file `entityForm.js` can make the 'media' tab functional, but the style needs tuning. My version is 5.0.5 GA.

![default](https://user-images.githubusercontent.com/9673067/27114663-beef6358-50f7-11e7-8ea5-86701f354c88.PNG)
