### ISSUE TITLE
XML merge fails for RuntimeEnvironmentPropertiesConfigurer

### ISSUE THREAD

**Issue by achepey** [BroadleafCommerce/BroadleafCommerce#1579]
When trying to add the environment properties to the RuntimeEnvironmentPropertiesConfigurer bean in my applicationContext.xml, it causes the resolver to not resolve any enterprise module properties. 

Here is a snippet of my addition to the bean:

`	<bean id="blConfiguration" class="org.broadleafcommerce.common.config.RuntimeEnvironmentPropertiesConfigurer" >
        <property name="environments">
            <set>
                <value>development</value>
            </set>
        </property>
    </bean>
`

**Comment by ktisdell** [comment]
You should not need to define or override that bean as it is registered by default.  `development` is the default environment.  To activate a different environment, you can set a system property (e.g. `-Druntime.environment=production`).
