### ISSUE TITLE
where to get 5.1.1  source codes?

### ISSUE THREAD

**Issue by chenshao0594** [BroadleafCommerce/BroadleafCommerce#1580]
As title
   Someone help me ?  
   thx

**Comment by feitian124** [comment]
i have similar question, does community version still be open sourced?
where can we get the souce code.

**Comment by linuxidefix** [comment]
- For 5.X version, to sum it up, Community is open source BUT :
1) Sources* are not available on Github but are available via maven, sources are downloaded automatically by your modern IDE.
2) They publish their source code only when they get something quite stable, so as part of a release
3) You won't see daily commits on github
4) Community is only for small business, read license detail for more details. It you buy a license, you will get more.

*Example:
http://nexus.broadleafcommerce.org/nexus/content/groups/community-releases/org/broadleafcommerce/broadleaf-common/5.1.1-GA/broadleaf-common-5.1.1-GA-sources.jar
ps: i'm not working for Broadleaf

**Comment by linuxidefix** [comment]
I dont' know if member of the Broadleaf team will read this but:
on point 1), yes it works. But it think it will be very helpful to publish (manually?) sometimes a tag or a release or a zip for a release, like you did for https://github.com/BroadleafCommerce/DemoSite/releases
- Main problem is search via IDE is not always accurate or slow. It is more easy to quickly search via Github search sometimes or search only on one downloaded source folder.
- Another (minor) problem is fix or pull request may not be easy when you are not on Github.

**Comment by feitian124** [comment]
i totally agree with @linuxidefix, if open sourced i hope make us more convenient to get source code and communicate

**Comment by phillipuniverse** [comment]
Just a heads up that we have now moved all of our code back onto GitHub, retroactive for all 5.x versions. We had previously forked this repository and all of the work within the 5.x line was done there. Sorry for the confusion.
