### ISSUE TITLE
error on ProductCustomPersistenceHandler when fetch

### ISSUE THREAD

**Issue by kunner** [BroadleafCommerce/BroadleafCommerce#1582]
I think there is an error on ProductCustomPersistenceHandler.

look, line 174 ~ 184 below,

`CriteriaBuilder builder = dynamicEntityDao.getStandardEntityManager().getCriteriaBuilder();
                CriteriaQuery<Long> criteria = builder.createQuery(Long.class);
                Root<CategoryProductXrefImpl> root = criteria.from(CategoryProductXrefImpl.class);
                criteria.select(root.get("product").get("id").as(Long.class));
                List<Predicate> restrictions = new ArrayList<Predicate>();
                restrictions.add(builder.equal(root.get("defaultReference"), Boolean.TRUE));
                if (CollectionUtils.isNotEmpty(transformedValues)) {
                    restrictions.add(root.get("category").get("id").in(transformedValues));
                }
                //archived?
                QueryUtils.notArchived(builder, restrictions, root, "archiveStatus");`

as this code, 'root' variable is CategoryProductXrefImpl.
but there is no archiveStatus in CategoryProductXrefImpl, but CategoryImpl and ProductImpl has it.

So, I think it need to change some code at line 184 like below.

`QueryUtils.notArchived(builder, restrictions, root.get("product"), "archiveStatus");
 QueryUtils.notArchived(builder, restrictions, root.get("category"), "archiveStatus");`

Please patch it, thx.

**Comment by kunner** [comment]
It occurred at v4.0.17 GA.

**Comment by danielcolgrove** [comment]
Fixed in more recent versions
