### ISSUE TITLE
EntityFormAction confirmEnabledText should use MessageSource

### ISSUE THREAD

**Issue by tonyharrison** [BroadleafCommerce/BroadleafCommerce#1584]
Version 5.1.1-GA
Expectation: confirmEnabledText property should be a message key rather than the literal message.

Fix requires modification to __open_admin_style/templates/layout/partial/entityTitle.html_ in _broadleaf-open-admin-platform_.

Replace occurrences of:
     _data-confirm-text=${action.confirmEnabledText}_
With
    _data-confirm-text=${#messages.msgOrNull(action.confirmEnabledText)}_

This should:
- Display the confirm.js default text if  confirmEnabledText is not set
- Display the message key if confirmEnabledText is set but there is no message for the key
- Display the message from MessageSource if confirmEnabledText is set and message for key exists.

**Comment by oleksiimiroshnyk** [comment]
as confirmEnableText is set in server side you can use BLCMessageUtils.getMessage("xxx")
