### ISSUE TITLE
how to customize a catalog and display my products

### ISSUE THREAD

**Issue by ShadowWalker-L** [BroadleafCommerce/BroadleafCommerce#1586]
I customized a catalog, and I want to add my products to the category and displayed in the front end.But it turned out that it was empty. I tries many ways but still couldn't solve the problem. I'd be highly appreciate if anyone can tell me a solution. Thanks in advance.
[https://i.stack.imgur.com/mhrJy.png](url)
[https://i.stack.imgur.com/lhJ6f.png](url)

**Comment by linuxidefix** [comment]
It depends on which Blc version  you are using: 
In Blc 5.x Demo, the product indexation is triggered every hour but not in Community Starter where scheduling config seems to be missing. ( i may post an issue for that on the CommunityStarter repo)

You can change the configuration in _runtime-properties/common.properties_ 
`solr.index.repeat.interval=3600000`

This property is used in : applicationContext.xml in DemoSite/site
```
<bean id="rebuildIndexTrigger" class="org.springframework.scheduling.quartz.SimpleTriggerFactoryBean">
        <property name="jobDetail" ref="rebuildIndexJobDetail" />
        <property name="startDelay" value="${solr.index.start.delay}" />
        <property name="repeatInterval" value="${solr.index.repeat.interval}" />
    </bean>
```

**Comment by phillipuniverse** [comment]
@ShadowWalker-L yes, indexing happens every hour depending on what you have that property set to.

@linuxidefix agree this should be in BroadleafCommerce/CommunityStarter, opening an issue there.
