### ISSUE TITLE
Anonymous user fail to add to cart "Attempting to save a customer with an id that already exists"

### ISSUE THREAD

**Issue by mohabshihab** [BroadleafCommerce/BroadleafCommerce#1587]
**Sometimes when multiple anonymous customer trying to add to cart, I get the following exception:**
Attempting to save a customer with an id that already exists in the database. 
This can occur when legacy customers have been migrated to Broadleaf customers, but the batchStart setting has not been declared for id generation. In such a case, the defaultBatchStart property of IdGenerationDaoImpl (spring id of blIdGenerationDao) should be set to the appropriate start value

**But I actually don't have any migrated data and already started from clean database**

many thanks for support

**Comment by oleksiimiroshnyk** [comment]
can't reproduce
