### ISSUE TITLE
Is it possible to change solr to ElasticSearch?

### ISSUE THREAD

**Issue by davidka92** [BroadleafCommerce/BroadleafCommerce#1636]
Is it possible to change solr to ElasticSearch? What is your experience on this matter? Do you know how long would it take/how hard would it be? Did you experience any performance difference after the change?
Thanks! :)

**Comment by ktisdell** [comment]
If using Community edition, it is possible to switch to ElasticSearch by re-implementing Broadleaf's `org.broadleafcommerce.core.search.service.SearchService` and implementing something to handle indexing (see `org.broadleafcommerce.core.search.service.solr.SolrIndexService`).  These are currently Community components.  However, we do not currently support this approach with Broadleaf's commercial features, which provide a number of advanced features related to indexing and searching with Solr.  We currently recommend SolrCloud, and only officially support integration with Solr at the moment.
