### ISSUE TITLE
ThymeleafMessageCreator alternative on 5.2?

### ISSUE THREAD

**Issue by droyop** [BroadleafCommerce/BroadleafCommerce#1709]
Hi,

Currently migrating form broadleaf 4 to broadleaf 5.2

ThymeleafMessageCreator just vanished from the code base but [the documentation](https://www.broadleafcommerce.com/docs/core/current/broadleaf-concepts/additional-configuration/email-configuration) still mentions it as the alternative

**Comment by phillipuniverse** [comment]
In Broadleaf 5.1, we migrated away from all Thymeleaf classes being within the Broadleaf framework. The class that you are specifically referenced is now located at https://github.com/BroadleafCommerce/PresentationLayer/blob/develop-1.1.x/broadleaf-thymeleaf3-presentation/src/main/java/org/broadleafcommerce/presentation/thymeleaf3/email/BroadleafThymeleaf3MessageCreator.java. You can read more about it in the [5.1 migration notes](https://www.broadleafcommerce.com/docs/core/current/migration-notes/5.1-thymeleaf-migration).

Thanks for mentioning the documentation, that particular section missed the update for 5.2.
