### ISSUE TITLE
Compilation error: log variable cannot be resolved

### ISSUE THREAD

**Issue by hamza00111** [BroadleafCommerce/BroadleafCommerce#1725]
In OptimisticLockUtils class in project ( Broadleaf common ), variable "log" is used but not created so the project does not compile

**Comment by danielcolgrove** [comment]
There are no details as to which version of Broadleaf this issue was found.

**Comment by zaghost** [comment]
log variable cannot be resolved in class:org.broadleafcommerce.common.util.OptimisticLockUtils
This issue exists in
1.https://github.com/BroadleafCommerce/BroadleafCommerce/archive/broadleaf-5.2.5-GA.zip
2.http://nexus.broadleafcommerce.org/nexus/content/groups/community-releases/org/broadleafcommerce/broadleaf-common/5.2.5-GA/broadleaf-common-5.2.5-GA-sources.jar

But, I decompiled http://nexus.broadleafcommerce.org/nexus/content/groups/community-releases/org/broadleafcommerce/broadleaf-common/5.2.5-GA/broadleaf-common-5.2.5-GA.jar, and I found it's fixed!
