### ISSUE TITLE
How to use Stand Alone Solr Server

### ISSUE THREAD

**Issue by squallzhou** [BroadleafCommerce/BroadleafCommerce#1734]
I follow the document to set up stand along solr server.
In the step,  I can't work, because I can't find the file of "site/src/main/resources/solrconfig.xml"!!

Where is this document?

<img width="790" alt="default" src="https://user-images.githubusercontent.com/11225093/32271174-a230cbee-bf33-11e7-9c6f-43e4a3518134.png">

**Comment by benhenda89** [comment]
see this file 
[solrconfig.xml](https://github.com/BroadleafCommerce/LegacyDemoSite/blob/develop-5.1.x/site/src/main/resources/solrconfig.xml)

**Comment by squallzhou** [comment]
Thanks!
So I should study “LegacyDemoSite”, the document should be based on this project.
it have not use springboot.

The newest site demo use springboot, there are a lot of defferents with the document.

Thanks a lot!
