### ISSUE TITLE
mvn install failed in BroadleafCommerce-broadleaf-5.0.13-GA Relase.

### ISSUE THREAD

**Issue by shengchuan1** [BroadleafCommerce/BroadleafCommerce#1735]
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.051 s
[INFO] Finished at: 2017-11-01T20:59:07+08:00
[INFO] Final Memory: 11M/150M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project broadleaf-open-admin-platform: Could n
ot resolve dependencies for project org.broadleafcommerce:broadleaf-open-admin-p
latform:jar:5.0.13-GA: Failure to find org.broadleafcommerce:broadleaf-common:ja
r:tests:5.0.13-GA

**Comment by danielcolgrove** [comment]
@shengchuan1 I was not able to recreate this issue.  Steps:

1) downloaded broadleaf 5.0.13-GA (https://github.com/BroadleafCommerce/BroadleafCommerce/releases/tag/broadleaf-5.0.13-GA)
2) from the root of the project, run `mvn clean install` which ran to completion.
