### ISSUE TITLE
Error While Adding Products To The Cart

### ISSUE THREAD

**Issue by santoshraju621** [BroadleafCommerce/BroadleafCommerce#1748]
Hi I Have Tried to add the products from merchandise-Men and  merchandise-Women it will gives the following error while adding  Products to the Cart.  

Here is the screen shot of the Error:   

http://i.prntscr.com/Dr_5CBezQKWIEOKGanBbZw.png   

Here is the Server Log of Error:  

http://i.prntscr.com/6FML0e3QQleo4vV_fL_6xQ.png  

Please Help to Solve the problem. 

 Thanks In Advance

**Comment by danielcolgrove** [comment]
@santoshraju621 I was not able to recreate this issue.  Steps:
1) downloaded 5.2.2.1-GA from github (https://github.com/BroadleafCommerce/DemoSite/releases)
2) run `mvn clean install` from root of the project
3) `cd site` and then  `mvn spring-boot:run`
4) navigated to `https://localhost:8443` and added men's shirt to the cart

**Comment by oleksiimiroshnyk** [comment]
can't reproduce
