### ISSUE TITLE
Broadleaf Custom controller calling failed

### ISSUE THREAD

**Issue by santoshraju621** [BroadleafCommerce/BroadleafCommerce#1752]
hi i have created a custom controller this will giving the exception at runtime

here is my custom controller code:

`       

          
           @Controller
          @RequestMapping("/"+Test12.SECTION_KEY)
          @Secured("ROLE_ADMIN")
           public class Test12  extends AdminAbstractController{
	 protected static final String SECTION_KEY = "test";
	

         public static String nme1="";
	

        // @Autowired
	 FilterExtra td;
	
	 @RequestMapping(value = "", method = RequestMethod.GET)
	    public String test(HttpServletRequest request, HttpServletResponse response, Model model) throws Exception {
	        // This is expected by the modules/emptyContainer template, this is a custom template that gets included into the body
	        model.addAttribute("customView", "views/test");

	        // ensure navigation gets set up correctly
	        setModelAttributes(model, SECTION_KEY);

	        // gets the scaffolding set up to display the template from the customView attribute above
	        return "modules/emptyContainer";
	    }
		//@RequestMapping(value = "check/{name}", method = RequestMethod.GET)
		 @RequestMapping(
			        value = {"/check/{name}"},
			        method = {RequestMethod.GET}
			    )
	public String check(HttpServletRequest request, HttpServletResponse response,Model model,  @PathVariable(value="name") String name,BindingResult result, RedirectAttributes ra) throws Exception{
			
			System.out.println(name);
			String available=td.check1(name);
			if(name.equals(available)) {
				nme1=name;
			model.addAttribute("customView", "views/sucess");
			setModelAttributes(model, SECTION_KEY);
			 return "modules/emptyContainer";
			}
			else {
				model.addAttribute("customView", "views/error");
				setModelAttributes(model, SECTION_KEY);
				 return "modules/emptyContainer";
			}
			}
	/*	@RequestMapping(value = "add/{name1}", method = RequestMethod.GET)
		public String add(HttpServletRequest request, HttpServletResponse response,Model model,    @PathVariable(value="name") String name1) {
				
				System.out.println(name1);
				String available=td.add(nme1,name1);
				if(available.equals("sucess")) {
				model.addAttribute("customView", "views/sucess1");
				setModelAttributes(model, SECTION_KEY);
				 return "modules/emptyContainer";
				}
				else {
					model.addAttribute("customView", "views/error");
					setModelAttributes(model, SECTION_KEY);
					 return "modules/emptyContainer";
				}
				}  */ }
`

Here is the exception caused at runtime:

> Sorry, there was an error processing your request. : b2012097-870f- 4e7b-8871-e82844a3cd23

here is the serverlog:

> java.lang.IllegalArgumentException: 'name' must not be null at org.springframework.util.Assert.notNull(Assert.java:134) ~[spring-core-4.3.9.RELEASE.jar:4.3.9.RELEASE] at org.springframework.beans.factory.BeanFactoryUtils.transformedBeanName(BeanFactoryUtils.java:72) ~[spring-beans-4.3.9.RELEASE.jar:4.3.9.RELEASE] at org.springframework.beans.factory.support.AbstractBeanFactory.transformedBeanName(AbstractBeanFactory.java:1117) ~[spring-beans-4.3.9.RELEASE.jar:4.3.9.RELEASE] at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:239) ~[spring-beans-4.3.9.RELEASE.jar:4.3.9.RELEASE] at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.3.9.RELEASE.jar:4.3.9.RELEASE] at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1078) ~[spring-context-4.3.9.RELEASE.jar:4.3.9.RELEASE] at org.broadleafcommerce.common.persistence.EntityConfiguration.lookupEntityClass(EntityConfiguration.java:75) ~[broadleaf-common-5.2.0-GA.jar:na] at 

Here is the HTML code:

```
<div class="row">
    <div class="twelve columns">
      <p> &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbspThis is a test</p>
       <form name="filtr" action="test/check/">
             FilterName: <input type="text" name="name" method="get">
             <input type="submit" value="checkfilter">
       </form>
   
    </div>
 </div>
```

Please Help me to Solve the issue

**Comment by ghost** [comment]
The attributes are incorrect and it's causing spring to reject the request.  "name" is not a path variable, it's a request parameter or model attribute, so if you change the RequestMapping and method signature it will work.  Also, the success view might be mispelled.


Try this instead:

```
    @RequestMapping(value = { "/check" }, method = { RequestMethod.GET } )
    public String check(HttpServletRequest request, Model model, @ModelAttribute("name") String name, BindingResult result, RedirectAttributes redirectAttributes) throws Exception {
        System.out.println(name);
        String available=name; //td.check1(name);
        if (name.equals(available)) { ................

```

**Comment by oleksiimiroshnyk** [comment]
I'm able to create new controller, can't reproduce
