### ISSUE TITLE
Compilation error on OptimisticLockUtils class in 5.2.x branch 

### ISSUE THREAD

**Issue by hamza00111** [BroadleafCommerce/BroadleafCommerce#1793]
Hi, 

When I import the broadleaf framework I find a compilation error of a missing declaration of a variable 'log'.

**Comment by danielcolgrove** [comment]
@hamza00111 We are using Lombok for the logging in that Class.  The annotation @CommonLog handles the inclusion of the `log`.

See https://projectlombok.org/api/lombok/extern/apachecommons/CommonsLog.html
