### ISSUE TITLE
Creating a New Custom Entity Admin Application error

### ISSUE THREAD

**Issue by vkhatri87** [BroadleafCommerce/BroadleafCommerce#1821]
I have created a new custom entity by following the below mentioned url steps "https://www.broadleafcommerce.com/docs/core/current/tutorials/core-tutorials/creating-a-new-entity"

The problem is that after creating a new custom entity the site application runs perfectly fine but i am getting a error while running a admin application.
I have removed the Jrebel and deleted the repository folder of .m2 maven repository and done the fresh re installation using command prompt.
But after doing this still i am unable to resolve the issue, below is an error log.

   at org.springframework.beans.factory.support.AbstractAutowireCapableBean
Factory.initializeBean(AbstractAutowireCapableBeanFactory.java:1624) ~[spring-be
ans-4.3.10.RELEASE.jar:4.3.10.RELEASE]
        ... 109 common frames omitted

**Caused by: java.lang.ClassNotFoundException: com.community.controller.account.RF
SDeliveryDetailsImpl**

        at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0
_111]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_111]

        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) ~[na:1.
8.0_111]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_111]

        at java.lang.Class.forName0(Native Method) ~[na:1.8.0_111]
        at java.lang.Class.forName(Class.java:348) ~[na:1.8.0_111]
        at org.broadleafcommerce.common.extensibility.jpa.MergePersistenceUnitMa
nager.triggerClassLoadForManagedClasses(MergePersistenceUnitManager.java:356) ~[
broadleaf-common-5.2.2-GA.jar:na]
        at org.broadleafcommerce.common.extensibility.jpa.MergePersistenceUnitMa
nager.preparePersistenceUnitInfos(MergePersistenceUnitManager.java:163) ~[broadl
eaf-common-5.2.2-GA.jar:na]
        ... 112 common frames omitted

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 27.596 s
[INFO] Finished at: 2018-03-08T23:31:18+05:30
[INFO] Final Memory: 22M/53M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.springframework.boot:spring-boot-maven-plugin
:1.5.6.RELEASE:run (default-cli) on project boot-community-demo-admin: Could not
 exec java: Application finished with exit code: 1 -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit

**my entity file sourcecode:**
RFSDeliveryDetailsImpl .java

package com.community.controller.account;

@Entity
@Table(name = "RFS_DELIVERY_DETAILS")
@Cache(usage=CacheConcurrencyStrategy.NONSTRICT_READ_WRITE, region="blOrderElements")
public class RFSDeliveryDetailsImpl implements RFSDeliveryDetails {

	private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue(generator = "ddId")
    @GenericGenerator(
        name="ddId",
        strategy="org.broadleafcommerce.common.persistence.IdOverrideTableGenerator",
        parameters = {
            @Parameter(name="segment_value", value="RFSDeliveryDetailsImpl"),
            @Parameter(name="entity_name", 
            value="com.community.controller.account.RFSDeliveryDetailsImpl")
        }
    )
    @Column(name = "DD_ID")
    protected Long ddId;
    
    @Column(name = "DELIVERY_DATE")
    @AdminPresentation(friendlyName = "RFSDELIVERYDETAILSImpl_deliveryDate", order=1, group = "RFSDELIVERYDETAILSImpl_deliveryDate")
    protected String deliveryDate;
    
    @ManyToOne(targetEntity = OrderImpl.class, optional=false, cascade = CascadeType.REFRESH)
    @JoinColumn(name = "ORDER_ID", nullable = false)
    @AdminPresentationToOneLookup()
    protected Order order;

	// getters and setters
    
}

also made an entry in persistence-core.xml 

<persistence xmlns="http://java.sun.com/xml/ns/persistence"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="http://java.sun.com/xml/ns/persistence http://java.sun.com/xml/ns/persistence/persistence_2_0.xsd"
             version="2.0">

    <persistence-unit name="blPU" transaction-type="RESOURCE_LOCAL">
        <non-jta-data-source>jdbc/web</non-jta-data-source>
        <class>com.community.controller.account.RFSDeliveryDetailsImpl</class>
        <exclude-unlisted-classes/>
    </persistence-unit>

please help me to resolve it.
Thanks in advance

**Comment by linuxidefix** [comment]
Did you create your entities in the core module ?
Doing that your entities will be reachable by the admin and the core modules.
Don't forget to do mvn clean install on the core module.

**Comment by vkhatri87** [comment]
Thanks alot..
Entity was not created in core module, after moving and doing appropriate changes issue is resolved
