### ISSUE TITLE
Regarding Cross Sale at Products level

### ISSUE THREAD

**Issue by vkhatri87** [BroadleafCommerce/BroadleafCommerce#1824]
Hi Team,
    I am having a certain confusion for showing a cross sale products, i want to display few cross sale products for a Particular product and not at  a Category Level.
For this i have clicked on Catalog -- > Products -- > Marketing and added a bunch of Cross Sale Products.
After doing it i am unable to see any of the added cross sale products.
Sorry for such elementary  question, Please suggest do i have to do anything extra for showing it like changing the products.html etc.
if yes what should be changed to display cross sale products.
Thanks in advance..
Best Regards,
Vishnu Khatri

**Comment by oleksiimiroshnyk** [comment]
hi @vkhatri87 
Depdends where you want to see cross sale products you need to add them to the model in controller and render in corresponding html
