### ISSUE TITLE
[Demo Site] 5.2.2.1 GA - Unable to swap cores

### ISSUE THREAD

**Issue by nhducseuit** [BroadleafCommerce/BroadleafCommerce#1837]
I got this message while follow the `Getting Started` guide with latest Demo source code 5.2.2.1 GA:
`org.broadleafcommerce.common.exception.ServiceException: Unable to swap cores`
My system:
```
MacOS Sierra 10.12.6 - 8GB RAM
```
I have tried to clean the M2 repo folder and re-run `mvn install` without success.
Could anyone spot me the place I need to correct?

**UPDATE:**
The log says
```
Started Solr server on port 8983 (pid=814). Happy searching!

2018-03-31 19:18:27.935 ERROR 709 --- [           main] c.b.solr.autoconfigure.SolrServer        : Problem while checking core status: javax.xml.transform.TransformerException: Unknown error in XPath.
2018-03-31 19:18:27.935 ERROR 709 --- [           main] c.b.solr.autoconfigure.SolrServer        : Unable to verify solr core status. Proceeding with startup.
```
I also not able to find the process with pid-814 as the log reported.
Could there be a problem with Solr server?

**UPDATE 2:**
Not sure this is related but what is ESAPI and should these logs be ignored?
```
2018-03-31 19:18:31.871  INFO 709 --- [           main] o.b.c.s.s.s.index.SolrIndexServiceImpl   : Rebuilding the entire Solr index...
Attempting to load ESAPI.properties via file I/O.
Attempting to load ESAPI.properties as resource file via file I/O.
Not found in 'org.owasp.esapi.resources' directory or file not readable: /Users/ducnh/Workspace/broadleaf/DemoSite-broadleaf-5.2.2.1-GA/admin/ESAPI.properties
Not found in SystemResource Directory/resourceDirectory (this should never happen): /Users/ducnh/Workspace/broadleaf/DemoSite-broadleaf-5.2.2.1-GA/admin/file:/Users/ducnh/.m2/repository/org/broadleafcommerce/broadleaf-common/5.2.2-GA/broadleaf-common-5.2.2-GA.jar!/esapi/ESAPI.properties
Not found in 'user.home' (/Users/ducnh) directory: /Users/ducnh/esapi/ESAPI.properties
Loading ESAPI.properties via file I/O failed. Exception was: java.io.FileNotFoundException
Attempting to load ESAPI.properties via the classpath.
SUCCESSFULLY LOADED ESAPI.properties via the CLASSPATH from 'esapi/' using current thread context class loader!
Attempting to load validation.properties via file I/O.
Attempting to load validation.properties as resource file via file I/O.
Not found in 'org.owasp.esapi.resources' directory or file not readable: /Users/ducnh/Workspace/broadleaf/DemoSite-broadleaf-5.2.2.1-GA/admin/validation.properties
Not found in SystemResource Directory/resourceDirectory (this should never happen): /Users/ducnh/Workspace/broadleaf/DemoSite-broadleaf-5.2.2.1-GA/admin/file:/Users/ducnh/.m2/repository/org/broadleafcommerce/broadleaf-common/5.2.2-GA/broadleaf-common-5.2.2-GA.jar!/esapi/validation.properties
Not found in 'user.home' (/Users/ducnh) directory: /Users/ducnh/esapi/validation.properties
Loading validation.properties via file I/O failed.
Attempting to load validation.properties via the classpath.
SUCCESSFULLY LOADED validation.properties via the CLASSPATH from 'esapi/' using current thread context class loader!
```

**UPDATE 3:**
Please see the solr server log attached.
[solr-8983-console.log](https://github.com/BroadleafCommerce/BroadleafCommerce/files/1865479/solr-8983-console.log)

**Comment by danielcolgrove** [comment]
@nhducseuit The ESAPI Info log is expected.  Something to try...boot up Broadleaf and let the Solr instance start up (even with errors).  Goto http://localhost:8983.  Using the left nav, goto "Core Admin".  If there are cores defined, Unload each one and then restart your Broadleaf instance.  I'm thinking that the core creation process had an error.  This is just starting that process fresh.  Hopefully that will get you past the error.

**Comment by nhducseuit** [comment]
@danielcolgrove  Thanks for the response.
I booted up admin but solr server got shutdown during the boot up process so I wasn't able to process further.
Please see the log attached
[admin.log](https://github.com/BroadleafCommerce/BroadleafCommerce/files/1867093/admin.log)

**Comment by nhducseuit** [comment]
I was able to manually start Solr server with

```/var/folders/56/wyvc3qtn6nbczck6bpyv2sqc0000gn/T/solr-5.3.1/solr-5.3.1/bin/solr start```

,went to `localhost:8983`, unloaded all cores then stopped the server before booting up admin site.

Still same error.

**Comment by danielcolgrove** [comment]
It appears that the application is having issues creating the cores on startup.  There are no specific exceptions other than the catalog core missing.

The error occurs when it's checking the core status.  It would be interesting to know what this returns: http://localhost:8983/solr/admin/cores?action=STATUS&indexInfo=false

Another potential work around is to start the solr server manually (like you did previously to unload the cores) and just use that instance.  Taking this approach, the application fines solr already running on port 8983 and doesn't try to start a new instance.  If the SolrStarter process is having issues getting a clean instance up, perhaps this will help.

I just downloaded and started up without an issue.  I'm not quite sure why your environment is having these errors.

**Comment by nhducseuit** [comment]
Thanks for your reply.
I will try your link with manually started Solr server to try reproduce the issue. Thanks.
