### ISSUE TITLE
丢失broadleaf-common-presentation

### ISSUE THREAD

**Issue by hongbeiti** [BroadleafCommerce/BroadleafCommerce#1880]
<dependency>
            <groupId>org.broadleafcommerce</groupId>
            <artifactId>broadleaf-common-presentation</artifactId>
            <version>${broadleaf-presentation.version}</version>
 </dependency>

这个依赖在哪下载？

**Comment by odirus** [comment]
> org.broadleafcommerce broadleaf-common-presentation ${broadleaf-presentation.version}
> 这个依赖在哪下载？

https://github.com/BroadleafCommerce/CommonPresentation
