### ISSUE TITLE
DemoOracleSingleLineSqlCommandExtractor does not support UPDATE statements

### ISSUE THREAD

**Issue by JustinCRL** [BroadleafCommerce/BroadleafCommerce#1896]
The DemoOracleSingleLineSqlCommandExtractor will convert the following:
UPDATE FOO SET BAR='BAZ' WHERE ID=1;
to
UPDATE (FOO SET BAR='BAZ' WHERE ID=1)
which will fail to run no Oracle

The "multi-row" logic in the class should not try to execute on UPDATE statements.

**Comment by oleksiimiroshnyk** [comment]
can't reproduce on 5.2.14
```java
        DemoOracleSingleLineSqlCommandExtractor extractor = new DemoOracleSingleLineSqlCommandExtractor();
        String[] strings = extractor.extractCommands(new StringReader("UPDATE FOO SET BAR='BAZ' WHERE ID=1;"));
```
returns UPDATE FOO SET BAR='BAZ' WHERE ID=1

**Comment by JustinCRL** [comment]
Did you run in Oracle.  This is during setup.
