### ISSUE TITLE
Multiple Validation Errors Creating a Product Breaks Selecting a Category

### ISSUE THREAD

**Issue by Hashmi42** [BroadleafCommerce/BroadleafCommerce#1938]
Steps to recreate:

1: Click Add New Product
2: Leave MSRP, Name, and Parent Category blank
3: Override URL to whatever you like, I chose /junk
4: Click save
5: Validation for MSRP, Name, and Parent Category appears
6: Fill in Name
6: Save
7: Fill in MSRP
8: Save
9: Fill in Parent Category

This is where the error gets thrown. The user is prevented from clicking out or doing anything else. This error crashes the webpage. 
![screen shot 2018-06-20 at 4 57 02 pm](https://user-images.githubusercontent.com/22648769/41686801-06bc2356-74ab-11e8-8454-cced33238462.png)

**Comment by cja769** [comment]
This bug occurs in 5.2. Also note, to view the stack trace in the console you'll have to open the console before creating the bug because the DOM freezes after producing the bug.

**Comment by cja769** [comment]
Moved to https://github.com/BroadleafCommerce/QA/issues/3406
