### ISSUE TITLE
BLC_OFFER has column MARKETING_MESSASGE , should be MARKETING_MESSAGE

### ISSUE THREAD

**Issue by Digestivee** [BroadleafCommerce/BroadleafCommerce#2016]
https://github.com/BroadleafCommerce/BroadleafCommerce/blob/daac374be274e0d1214e94c0ec808b470dd28bfa/core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/offer/domain/OfferImpl.java

row 133 / 134

**Comment by cja769** [comment]
BroadleafCommerce/BroadleafCommerce#2252

Change can be consumed in the upcoming release of 6.1.0-GA
