### ISSUE TITLE
Update jQuery Version - Vulnerability in Current Library

### ISSUE THREAD

**Issue by spencerkordecki** [BroadleafCommerce/BroadleafCommerce#2108]
In the latest code on `develop`, the jQuery version being used is 1.9.1. This version is known to have XSS vulnerabilities and should be updated according to the reference here: https://snyk.io/vuln/npm:jquery

https://github.com/BroadleafCommerce/BroadleafCommerce/blob/develop/common/src/main/resources/common_style/js/lib/jquery-1.9.1.js

**Comment by StanislavFedorov** [comment]
I have investigated this issue. And my results are:

1. BLC 5.0 and 5.2 in the admin uses jquery-2.1.1.min.js but not 1.9.1 . According to https://snyk.io/vuln/npm:jquery  2.1.1 and 1.9.1  have the same vulnerables:  "Cross-site Scripting (XSS)" and "Prototype Pollution" (both marked as medium severity issues)

2. Site uses jquery-3.1.1.min.js that have only "Prototype Pollution" issue

3. There are only 2 version that have not any vulnerables: 3.4.0 and 3.4.1 (latest)

4. In any case to get rid from "Cross-site Scripting (XSS)" we need to move from 2.1.1 to some 3.x.x. 3.x.x and 2.x.x have not backward compatibility. So we need to check and rework (or to find a new versions) related JS modules.

5. I have made a quick test and have moved 5.2 admin from jquery- 2.1.1 to  jquery-3.4.1 and first that i have noticed - Datepicker had broken
