### ISSUE TITLE
SearchFacetImpl is missing archiveStatus

### ISSUE THREAD

**Issue by rahatjan** [BroadleafCommerce/BroadleafCommerce#2137]
Hi I have been waiting for a fix in SearchFacetImpl which is missing archiveStatus. Although in SearchFacetDaoImpl you are using archive status which is breaking search functionality.
```

Path<Character> archived = facet.get("archiveStatus").get("archived");
        Path<Character> archived = facet.get("archiveStatus").get("archived");

        criteria.where(
                builder.equal(facet.get("showOnSearch").as(Boolean.class), true),
                builder.or(builder.isNull(archived.as(String.class)),
                           builder.notEqual(archived.as(Character.class), 'Y')),
                builder.or(builder.isNull(archived.as(String.class)),
                           builder.notEqual(archived.as(Character.class), 'Y')),
                facet.join("fieldType")
                        .join("indexField")
                        .join("field")
```

The fix is very straight and simple just add the standard archiveStatus in the entity class like this which is working for me 

```

 @Embedded
    protected ArchiveStatus archiveStatus = new ArchiveStatus();
```

**Comment by jaumzera** [comment]
I was facing the same problem. Take a look at: https://stackoverflow.com/a/57964913/3120564

**Comment by StanislavFedorov** [comment]
Hello, Rahatjan.

It seems that you dont use spring-instrument.jar in your application.
You should have something like this in your VM option (if you starts in IDE):
-javaagent:/full/path/to/spring-instrument.jar

And here is link to Broadleafcommerce documentation: https://www.broadleafcommerce.com/docs/core/current/appendix/load-time-weaving
