### ISSUE TITLE
where is the package org.broadleafoverrides.admin.config

### ISSUE THREAD

**Issue by lyhsblog** [BroadleafCommerce/BroadleafCommerce#2142]
where is the package org.broadleafoverrides.admin.config

**Comment by phillipuniverse** [comment]
This is a package that you should create in your own project. It is manually included by Broadleaf and guaranteed to be the very last override for where you can declare beans within, say, an `@Configuration` class with `@Bean` methods.

So you create a class in your own project like this for bean overrides:

```java
package org.broadleafoverrides.admin.config;

@Configuration
public class BroadleafAdminOverrides {

    @Bean
    public ProductService blProductService() {
        return new MyProductService();
    }
}
```

This gets scanned in from right here in Broadleaf: https://github.com/BroadleafCommerce/BroadleafCommerce/blob/18af68cea8231335c5ad4b9cfb136059b44c7851/common/src/main/resources/override-contexts/admin-root-autoconfiguration-overrides.xml#L26-L29
