### ISSUE TITLE
TranslationServiceImpl is slow to provide translations for some pages

### ISSUE THREAD

**Issue by jefffischer** [BroadleafCommerce/BroadleafCommerce#219]
For pages that have a lot of translatable elements (e.g. the merchandise page in the heat clinic demo - each product has a number of product options/skus to translate as well), the TranslationService gets bogged down with translation requests and slows down page rendering. There is a cache in place, but it is ineffective because it does not take into account null responses. Since many of the translation requests result in null, these responses should be cached as well so that excessive database requests are not required.

**Comment by brundonsmith** [comment]
Commit e772307 was mistakenly linked here
