### ISSUE TITLE
Enhance performance of SystemPropertyImpl select by name queries by adding additional indexes

### ISSUE THREAD

**Issue by Novemser** [BroadleafCommerce/BroadleafCommerce#2216]
As `SystemPropertyImpl` is extensively queried by name across the application(e.g. in `SystemPropertiesServiceImpl.java`, `BLCSystemProperty.java`, etc.), adding an index on the column field `name` in `SystemPropertyImpl.java`(column `PROPERTY_NAME` in table `BLC_SYSTEM_PROPERTY`) might speed up the query, especially when the application stores a large number of rows in `BLC_SYSTEM_PROPERTY`.

**Comment by danielcolgrove** [comment]
@Novemser Thanks for opening this issue.  I went ahead and created a PR to be reviewed and merged.  On future issues you find, you are welcome to fork and submit a PR.
