### ISSUE TITLE
how to run on two server with static file?

### ISSUE THREAD

**Issue by epubreader** [BroadleafCommerce/BroadleafCommerce#2302]
how to run on two server with static file?
I want to rsync static files from one server to another server in real time.

thanks.

**Comment by danielcolgrove** [comment]
Best practice is to use a CDN provider - something like cloudflare or cloudfront.  You would need an integration to those providers.  If you want to share files on your local file servers, there are options like rsync or probably a better option, you can setup an NFS (network file service) with your nodes using a NFS client.  If you use the admin to upload assets, the admin would need to participate in the NFS setup as well.  All nodes would point to a common mount - something like "/broadleaf/assets"
