### ISSUE TITLE
Unable to find a suitable main class

### ISSUE THREAD

**Issue by kkrkuldeep** [BroadleafCommerce/BroadleafCommerce#2316]
- I clone the project from the repository and set up it to my system
- It builds successfully
- I do mvn spring-boot:run
- It says unable to find main class found
- I searched it but couldn't able to find any resource to fix that issue as there is no main class to load up the project
`[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] BroadleafCommerce                                                  [pom]
[INFO] BroadleafCommerce Common Libraries                                 [jar]
[INFO] BroadleafCommerce Core                                             [pom]
[INFO] BroadleafCommerce Profile                                          [jar]
[INFO] BroadleafCommerce Profile Web                                      [jar]
[INFO] BroadleafCommerce Framework                                        [jar]
[INFO] BroadleafCommerce Framework Web                                    [jar]
[INFO] BroadleafCommerce Admin                                            [pom]
[INFO] BroadleafCommerce Open Admin Platform                              [jar]
[INFO] BroadleafCommerce Admin Module                                     [jar]
[INFO] BroadleafCommerce CMS Module                                       [jar]
[INFO] BroadleafCommerce Integration                                      [jar]
[INFO] BroadleafCommerce Admin Functional Tests                           [jar]
[INFO]
[INFO] ------------------< org.broadleafcommerce:broadleaf >-------------------
[INFO] Building BroadleafCommerce 6.0.10-SNAPSHOT                        [1/13]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO]
[INFO] >>> spring-boot-maven-plugin:2.2.7.RELEASE:run (default-cli) > test-compile @ broadleaf >>>
[INFO]
[INFO] --- jacoco-maven-plugin:0.8.1:prepare-agent (default) @ broadleaf ---
[INFO] surefire.argLine set to -javaagent:/home/bajrang/.m2/repository/org/jacoco/org.jacoco.agent/0.8.1/org.jacoco.agent-0.8.1-runtime.jar=destfile=/home/bajrang/baju/mountblue/open-source/BroadleafCommerce/target/jacoco.exec
[INFO]
[INFO] --- license-maven-plugin:1.8:update-file-header (first) @ broadleaf ---
[INFO] adding extra resolver file:///home/bajrang/baju/mountblue/open-source/BroadleafCommerce//licenses
[WARNING] No file to scan.
[INFO]
[INFO]
[INFO] <<< spring-boot-maven-plugin:2.2.7.RELEASE:run (default-cli) < test-compile @ broadleaf <<<
[INFO]
[INFO]
[INFO] --- spring-boot-maven-plugin:2.2.7.RELEASE:run (default-cli) @ broadleaf ---
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for BroadleafCommerce 6.0.10-SNAPSHOT:
[INFO]
[INFO] BroadleafCommerce .................................. FAILURE [  3.130 s]
[INFO] BroadleafCommerce Common Libraries ................. SKIPPED
[INFO] BroadleafCommerce Core ............................. SKIPPED
[INFO] BroadleafCommerce Profile .......................... SKIPPED
[INFO] BroadleafCommerce Profile Web ...................... SKIPPED
[INFO] BroadleafCommerce Framework ........................ SKIPPED
[INFO] BroadleafCommerce Framework Web .................... SKIPPED
[INFO] BroadleafCommerce Admin ............................ SKIPPED
[INFO] BroadleafCommerce Open Admin Platform .............. SKIPPED
[INFO] BroadleafCommerce Admin Module ..................... SKIPPED
[INFO] BroadleafCommerce CMS Module ....................... SKIPPED
[INFO] BroadleafCommerce Integration ...................... SKIPPED
[INFO] BroadleafCommerce Admin Functional Tests ........... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.693 s
[INFO] Finished at: 2020-05-15T12:49:50+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:2.2.7.RELEASE:run (default-cli) on project broadleaf: Unable to find a suitable main class, please add a 'mainClass' property -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException`

![Screenshot from 2020-05-15 11-33-59](https://user-images.githubusercontent.com/35577324/82022073-a6c83700-96a9-11ea-9d1c-a2ae1a38621b.png)

**Comment by danielcolgrove** [comment]
Make sure that you `cd` into site, admin, or api.  Those are the application directories and is where you can run sprint-boot.

**Comment by kkrkuldeep** [comment]
> Make sure that you `cd` into site, admin, or api. Those are the application directories and is where you can run sprint-boot.

The project I am talking about is BroadleafCommerce/BroadleafCommerce there is no such directory like the site as you can see. (16 issues)

- The thing you tell me about is BroadleafCommerce/DemoSite which is different
- Both projects have different issues (3 issues)
- Both have different Repo's
- Here I give you the link of the Repository that you talking about

https://github.com/BroadleafCommerce/DemoSite

**Comment by danielcolgrove** [comment]
@kkrkuldeep Sorry, DemoSite is what I was referring to.  The Broadleaf module is a java library / java API.  It does not run standalone but is bundled with some type of "frontend" (website or rest api).  We provide the DemoSite as a starting point or a reference implementation for a site and/or api.
