### ISSUE TITLE
CustomerAddressDao does not remove the customer address

### ISSUE THREAD

**Issue by ghost** [BroadleafCommerce/BroadleafCommerce#2422]
- broadleaf-6.0.11-GA
- mysql 5.7.29

removing CustomerAddress does not work for me. I had to override the dao and remove the CustomerAddress from the owning side on customer.

`   @ Override
    public void deleteCustomerAddressById(Long customerAddressId) {
        CustomerAddress customerAddress = readCustomerAddressById(customerAddressId);
        Customer customer = customerAddress.getCustomer();
        customer.getCustomerAddresses().remove(customerAddress);
        em.merge(customer);
    }
`

**Comment by oleksiimiroshnyk** [comment]
that's expected. It should be archived...
