### ISSUE TITLE
SolrServer couldn't start on windows when demo sites(admin,site) start

### ISSUE THREAD

**Issue by StanislavIsaev** [BroadleafCommerce/BroadleafCommerce#2635]
Trying to start DemoSite and failed with error:

Invalid command-line option: true

Usage: solr start [-f] [-c] [-h hostname] [-p port] [-d directory] [-z zkHost] [-m memory] [-e example] [-s solr.solr.home] [-t solr.data.home] [-a "additional-options"] [-V]
...

OS: win10
branch: develop-6.2.x

The cause in com.broadleafcommerce.solr.autoconfigure.SolrServer, line 163

`String[] commands = {getSolrCommand(), "start", "-p", Integer.toString(props.getPort()), "-a", "-Dlog4j2.formatMsgNoLookups=true"};`

As solr help says:
  -a opts       Additional parameters to pass to the JVM when starting Solr, such as to setup
                Java debug options. For example, to enable a Java debugger to attach to the Solr JVM
                you could pass: -a "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=18983"
                In most cases, **you should wrap the additional parameters in double quotes.**

So, solution is to wrap "-Dlog4j2.formatMsgNoLookups=true" in additional double quotes

**Comment by oleksiimiroshnyk** [comment]
already fixed...
