### ISSUE TITLE
<div> tags sometimes get converted to <p> tags in Redactor

### ISSUE THREAD

**Issue by apazzolini** [BroadleafCommerce/BroadleafCommerce#339]

**Comment by PeterBloom** [comment]
Our app makes some HTML email templates with Redactor that we store and load.  `convertDivs: false` did not prevent Redactor from converting `<div>` to `<p>` upon file load.  We found through reading the redactor.js source that if we added the setting `replaceDivs: false` as an init parameter we got the behavior we wanted (load and save HTML with `<div>` elements as-is).  This seems to be an undocumented feature.

**Comment by buttflattery** [comment]
@PeterBloom  you need to use `replaceDivs:false`
