### ISSUE TITLE
Override Spring Social's JdbcUsersConnectionRepository - Forces a "UserConnection" named table

### ISSUE THREAD

**Issue by elbertbautista** [BroadleafCommerce/BroadleafCommerce#444]
Spring Social is  "hard-coded" to require a table name of any table prefix + "UserConnection"
http://static.springsource.org/spring-social/docs/1.0.x/reference/html/serviceprovider.html#service-providers-persisting-connections-jdbc

This conflicts with our all uppercase naming convention on tables and may cause issues with case sensitive db's

We need to provide our own implementation of the following class. There may be other classes that use the "UserConnection" table that need to be investigated.

see ln 84:
org.springframework.social.connect.jdbc.JdbcUsersConnectionRepository
List<String> localUserIds = jdbcTemplate.queryForList("select userId from " + tablePrefix + "UserConnection where providerId = ? and providerUserId = ?", String.class, key.getProviderId(), key.getProviderUserId());

**Comment by j-bron** [comment]
I find this design hard to work with as well. 

I am working with OAuth2 refresh tokens with google API. Refresh tokens are returned only on first OAuth2-dance from google servers. If user triggers second OAuth2 dance, the refresh token will not be returned. Then, the `Connection`gets updated with new data and previously saved refresh token is erased. I want to prevent erasing of the refresh token.

To add such behavior I have to change method `JdbcConnectionRepository.updateConnection(Connection<?> connection)`. With current design of the library it's impossible. Of course I can provide my own implementation of `ConnectionRepository` interface but I will be duplicating the class with one small change.
