### ISSUE TITLE
Do something besides just throw an exception in CsrfFilter

### ISSUE THREAD

**Issue by phillipuniverse** [BroadleafCommerce/BroadleafCommerce#518]
9 times out of 10 a bad CSRF token is because somebody sat on a form for too long. Rather than throwing an exception in the filter that a client has to know about modifying (you would never want to show a stack trace/error page to a user just for that) Broadleaf should have the ability to fail more gracefully.

It appears that GH handles this pretty well. I sat on a form for 30 minutes, tried to submit it and it simply kept me where I was (form didn't change at all) and I just had to hit the submit button again. Not sure what it's doing behind the scene, but something like that (maybe a notification) would be nice.

We did something similar already in the AdminCsrfFilter in the framework.

**Comment by deepubansal** [comment]
Is it OK to show an invalid session page to an end user who is not even logged in ?
He might get confused that I haven't even logged in then which session got expired !
