### ISSUE TITLE
Remove the dependency for Ejb3ConfigurationDao

### ISSUE THREAD

**Issue by phillipuniverse** [BroadleafCommerce/BroadleafCommerce#593]
This is currently only used in the admin, namely in `DynamicEntityDao`. It appears that the only reason for this Dao is to obtain Hibernate metadata about a particular class in order to ascertain things like which entity a field is related to or column lengths specified in `@Column` annotations.

However, Ejb3Configuration is deprecated as of Hibernate 4+. We could possibly remove the dependency on this class if we instead used the `ClassMetadata` from the `Session` object. When using an `EntityManagerFactory` there isn't really a way in Hibernate 4+ to get the `Configuration` and subsequently the Hibernate `PersistentClass`. It appears that the only way to do this is through a `SessionManagerFactory` and the only way to set that up is by explicitly telling Spring to use Hibernate (as opposed to a generic JPA provider).

This isn't causing an issue now but will likely be required as we upgrade Spring/Hibernate to later versions.

**Comment by RapidTransit** [comment]
I've been tooling with Hibernate 5, and some of these changes happened in versions of 4.x
Requires Spring 4.2
TableGenerator changed to use ServiceRegistry instead of Dialect on the configure method.
Packages from ```org.hibernate.ejb.``` are now ```org.hibernate.jpa```
```org.hibernate.cache.spi.CacheKey``` is gone
```org.hibernate.jmx.StatisticsService``` is gone
Use ```@Type(type = "org.hibernate.type.TextType")```  (I think?) because ```org.hibernate.type.StringClobType``` is gone
```org.hibernate.annotations.Index``` is deprecated use ```javax.persistence.Index```
To get metadata now use the Serviceloader:
```java
package org.broadleafcommerce.openadmin.server.dao;

import org.hibernate.boot.SessionFactoryBuilder;
import org.hibernate.boot.spi.MetadataImplementor;
import org.hibernate.boot.spi.SessionFactoryBuilderFactory;
import org.hibernate.boot.spi.SessionFactoryBuilderImplementor;

public class EntityMetaData implements SessionFactoryBuilderFactory {

    private static final ThreadLocal<MetadataImplementor> meta = new ThreadLocal<>();
    
    @Override
    public SessionFactoryBuilder getSessionFactoryBuilder(MetadataImplementor metadata, SessionFactoryBuilderImplementor defaultBuilder) {
        meta.set(metadata);
        return defaultBuilder;
    }

    public static MetadataImplementor getMeta() {
        return meta.get();
    }
}
```

**Comment by SpOOnman** [comment]
Ejb3Configuration is gone namely in Hibernate 4.3. Even worse, as @RapidTransit has mentioned Packages from `org.hibernate.ejb` are now `org.hibernate.jpa`. This breaks `DynamicEntityDao` and I cannot see an easy way to fix it.

I'd love to see Hibernate 4.3 in Broadleaf so I can use JPA 2.1 features.

**Comment by RapidTransit** [comment]
@SpOOnman The changes from migrating from 4.1 to 4.3 is drastic... So much so I think all the changes I made came from 4.3 that I just jumped to 5. I just put the master branch in my Gradle build (Along with a modified PG JDBC driver). Serious case of not invented here syndrome (In my defense it was taking longer for the driver to parse the queries than actually get the results!)

**Comment by SpOOnman** [comment]
I've managed to use Hibernate 4.3 in our project with BLC 4.0 dependency. Main steps are:

- exclude hibernate dependencies from BLC common dependecies
- include hibernate 4.3 dependencies
- create empty `public class Ejb3Configuration extends Configuration` in package `org.hibernate.ejb` as a fallback
- in presistence.xml add line `<provider>org.hibernate.ejb.HibernatePersistence</provider>`
- in presistence.xml add hibernate property `<property name="hibernate.discriminator.ignore_explicit_for_joined" value="true" />` for some legacy broken joined inheritance classes
- in bean entityManagerFactory add these two properties:
```xml
<property name="entityManagerFactoryInterface" value="org.hibernate.ejb.HibernateEntityManagerFactory" />
<property name="entityManagerInterface" value="org.hibernate.ejb.HibernateEntityManager" />
```
- create empty class to override exporter that uses StatisticsService that was removed from Hibernate 4.3: `<bean id="hibernateExporter" class="pl.touk.virgin.spitfire.core.util.EmptyExporter" />`

I hope that helps!

**Comment by RapidTransit** [comment]
Also the Old Cache key that Ecache is using is package protected `org.hibernate.cache.internal.OldCacheKeyImplementation`

Also I left out that you need to:
You will need the file:
`/resources/META-INF/services/org.hibernate.boot.spi.SessionFactoryBuilderFactory`
with the fully qualified class name, which in my example is:
`org.broadleafcommerce.openadmin.server.dao.EntityMetaData`
to get the `PersistentClass`
