### ISSUE TITLE
Consider lazy-loading @Lob String fields

### ISSUE THREAD

**Issue by phillipuniverse** [BroadleafCommerce/BroadleafCommerce#841]
@ktisdell ran into this with a client recently. The idea is that if you have a ton of data in a String @Lob, all of that data is returned on every query for that entity. Consider the case of pulling back a list of Skus. If every Sku has 100kb of data in the long description field, pulling back 100 Skus is a 10MB query result (at a minimum). This problem can be amplified with joining other entities that have the same type of `@Lob` field.

You can theoretically fix this with this annotation:

``` java
@Lob
@Basic(fetch = FetchType.LAZY)
@Type(type = "org.hibernate.type.StringClobType")
@Column(name = "LONG_DESCRIPTION", length = Integer.MAX_VALUE - 1)
protected String longDescription;
```

However, Hibernate doesn't respect this lazy fetchtype, presumably because it is a String field and it cannot wrap it.

But, you can provide some compile-time instrumentation via a Maven plugin:

``` xml
<plugin>
    <artifactId>maven-antrun-plugin</artifactId>
    <executions>
        <execution>
            <id>Instrument domain classes</id>
            <configuration>
                <tasks>
                    <taskdef name="instrument"
                             classname="org.hibernate.tool.instrument.javassist.InstrumentTask">
                        <classpath>
                            <path refid="maven.dependency.classpath"/>
                            <path refid="maven.plugin.classpath"/>
                        </classpath>
                    </taskdef>
                    <instrument verbose="true">
                        <fileset dir="${project.build.outputDirectory}">
                            <include name="org/broadleafcommerce/core/catalog/domain/*.class"/>
                        </fileset>
                    </instrument>
                </tasks>
            </configuration>
            <phase>process-classes</phase>
            <goals>
                <goal>run</goal>
            </goals>
        </execution>
    </executions>
</plugin>
```

I think it makes sense to add this build step to the framework.

**Comment by jefffischer** [comment]
Partially addressed by this commit: https://github.com/BroadleafCommerce/BroadleafCommercePrivate/commit/e90823c4c48898f5ea8a2bf7bf2b1e77cbe9daeb. Still requires the JPA property be set in the implementation for the persistence unit and the @Basic annotation be set on the CLOB fields in question.
