### ISSUE TITLE
Consolidate approach for deleting entities in the admin

### ISSUE THREAD

**Issue by phillipuniverse** [BroadleafCommerce/BroadleafCommerce#842]
General design around this between @jefffischer and I:
- Introduce a @SoftDelete annotation that will be dormant by default but when it's enabled it will add in an @Where clause for the archived status (going with @Where rather than @Filter because of the caching implications). This will work very similar to SandboxClassTransformer
- SandboxClassTransformer needs to be modified to allow to work with @Where annotations
- Keep ArchiveStatus as an embedded Character
  
  > Different databases treat booleans very differently (like Oracle)
- Remove all `@SqlDelete` annotations from entities in favor of having explicit DAO methods that perform a hard delete and a soft delete. A hard delete will perform a normal `em.remove()` while a soft delete will set archived = 'Y' and then do an `em.merge()`.
- Modify the admin such that when you perform a delete and the entity is archivable that the soft delete is performed utilizing `em.merge()` rather than `em.remove()`
- Cascade the archived from Product -> Skus. If you archive a Product, then the Skus for that product should also be archived. Unsure if this should occur in the service/dao APIs but it should definitely occur in the admin
- Provide messaging in the admin that if an entity fails to be deleted because of a foreign key constraint, link to docs about how you can modify that entity in order to have the soft-delete functionality
- Document (minimum) and write a blog post (nice-to-have) about the deletion behavior in the admin and how you can have your own custom entities be involved as well
  - Docs should also include how to modify an existing Broadleaf entity that we may not have thought of managing in the admin. For instance, if we decided to not ever soft-delete CustomerImpl but somebody that was using Broadleaf wanted this behavior. 

List of entities that should have this (common case is any top-level admin entities that could have foreign key constraints):
- Product
- Sku
- Customer
- Site
- Offer
- OfferCode
- OrderPayment
- PaymentTransaction
- ModuleConfiguration
- Page
- Structured Content
- System Property

This issue will also serve as a catch-all for all issues dealing with foreign key constraints due to deletes in the admin.

**Comment by eliteswap** [comment]
bpolster, I must be confused, I was under the impression that the open-source products included all of the "core" functionality, and the enterprise version added all sorts of additional specific code,  but this seems to be large part of the "core" code, am I missing something?

**Comment by taojiaenx** [comment]
@bpolster I can delete the product by using catalogSerivce sucessuflly and why it failed when I use the origin contorller? Is their SQL differenct, but they are delete the same class(Product), why their sql is different ?
