### ISSUE TITLE
Support for product option faceting

### ISSUE THREAD

**Issue by watermelonjuice** [BroadleafCommerce/BroadleafCommerce#859]
Add a color option of black, brown, or red, to a product. The matching product attributes should be added to the product so the "filter your results" is automatically populated.

**Comment by phillipuniverse** [comment]
Small point: the `FACET_FIELD_TYPE` for the entry in `BLC_FIELD` needs to be 'ss' (multivalued string). If you want it to be searchable then you need an entry into `BLC_FIELD_SEARCH_TYPES` with a `SEARCHABLE_FIELD_TYPE` of 'ss' as well.
