### ISSUE TITLE
PageNotFound - No mapping found for HTTP request with URI [/] in DispatcherServlet with name 'mycompany'

### ISSUE THREAD

**Issue by ghost** [BroadleafCommerce/BroadleafCommerce#865]
After I have migrated to Oracle 11g Database, I have got the following error. All the tables and views are created successfully in the Oracle Database, but this the problem I am left with.

**Comment by carlosv1989** [comment]
I have the same problem , i can see my admin and site/faq pages but the only page i cannot see is the site "home", and i have a 'Home' entry in BLC_CATEGORY

**Comment by josephmak** [comment]
See blc category . Make sure entries active date is valid

**Comment by carlosv1989** [comment]
Excellent man, thanks, i don't know why but all the register in that table has that date two hours in the future
(I am from Mexico City rigth now is 12:11 pm) 
It is working now

**Comment by josephmak** [comment]
Timezone related maybe. Broadleaf people didn't answer me... I just happen
to notice and figured out :)

**Comment by danielcolgrove** [comment]
Hi @josephmak and @carlosv1989 We try to encourage folks to ask any support related questions in the Broadleaf forums (forum.broadleafcommerce.org) or even use StackOverFlow with a `broadleaf-commerce` tag.  Both community members and members of the BLC team respond in those forums.
